CCExtractor/ccextractor

src/lib_ccx/608_sami.c, src/lib_ccx/608_smptett.c, src/lib_ccx/608_srt.c, src/lib_ccx/ccx_common_constants.c, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/ocr.c, src/lib_ccx/ocr.h, src/lib_ccx/spupng_encoder.c, src/lib_ccx/spupng_encoder.h
removed multiple warning from tesseract
Automatic language selection
if traindata not present, switch to
=> removed multiple warning from tesseract

mac/build.command
Hey. The build script didn't work on mac so I fixed it
=> Fixed mac build

src/lib_ccx/params.c
because of this many sub option which work on the param on selection of user did not work.
=> removing redundant init_options

src/ccextractor.c, src/lib_ccx/ccx_decoders_xds.h
In cleaning up following things contain.
1) Moving code in there respective file.
2) Indenting with tab instead of space.
3) removing global variable and putting them in context
Note: everything is not cleaned in one go, but it is in small patch
=> Cleaning Up code

src/ccextractor.c, src/lib_ccx/file_functions.c, src/lib_ccx/params.c, src/lib_ccx/ts_tables_epg.c
there are also some added space to add readability
=> Boundary condition check in EPG

src/CMakeLists.txt, src/lib_ccx/CMakeLists.txt
corrected failed build on linux using Cmake
=> linux build using Cmake

.gitignore, windows/ccextractor.vcxproj, windows/ccextractor.vcxproj.filters, windows/ccextractor.vcxproj.user
Basically fixes the Release build of the VS project and adds some more files to the gitignore.
=> Project VS fixes

src/lib_ccx/params.c
=> Corrected typos in help info

src/lib_ccx/608_spupng.c, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_decoders_608.c, src/lib_ccx/ccx_decoders_608.h, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/ccx_encoders_structs.h, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/output.c, src/lib_ccx/params.c, src/lib_ccx/stream_functions.c, src/lib_ccx/utility.c, src/lib_ccx/utility.h
=> remove compiler warnings

src/ccextractor.c, src/gpacmp4/mp4.c, src/lib_ccx/activity.h, src/lib_ccx/asf_functions.c, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/configuration.c, src/lib_ccx/es_functions.c, src/lib_ccx/file_functions.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/myth.c, src/lib_ccx/params.c, src/lib_ccx/params_dump.c, src/lib_ccx/sequencing.c, src/lib_ccx/stream_functions.c, src/lib_ccx/telxcc.c, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_tables.c, src/lib_ccx/ts_tables_epg.c, src/lib_ccx/utility.c, src/lib_ccx/wtv_functions.c
Changes Tested with willem testSuite
=> Making Demuxer Context

src/lib_ccx/asf_functions.c, src/lib_ccx/ccx_common_common.h, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_decoders_608.c, src/lib_ccx/ccx_decoders_608.h, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/ccx_encoders_helpers.c, src/lib_ccx/configuration.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/params.c, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_functions.h, src/lib_ccx/ts_tables.c, src/lib_ccx/ts_tables_epg.c, src/lib_ccx/wtv_functions.c
This pull request is tested with Willem TestSuite
=> Correcting Boundary condition

src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/lib_ccx.h, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_functions.h, src/lib_ccx/ts_tables.c
Add support for multi-packet PATs and PMTs in MPEGTS
=> Add support for multi-packet PATs and PMTs in MPEGTS

docs/OCR.txt, linux/Makefile
=> update linux related chages in ocr

src/lib_ccx/ccx_demuxer.h, src/lib_ccx/lib_ccx.h, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_tables.c, src/lib_ccx/ts_tables_epg.c
and using it to provide real channel names in EPG output.
=> Add support for parsing the Service Description Table in MPEGTS 

src/gpacmp4/mp4.c, src/lib_ccx/ccx_common_timing.c, src/lib_ccx/ccx_common_timing.h, src/lib_ccx/ccx_decoders_608.c, src/lib_ccx/ccx_decoders_708.c, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_common.h, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/ccx_decoders_xds.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/es_functions.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/myth.c
=> remove errors due to incorrect merge

src/lib_ccx/608_webvtt.c, src/lib_ccx/ccx_encoders_common.c
1) remove srt counter from webvtt
2) add include files so that compiler gives error at incorrect arguments in function call
3) WEBVTT Header do not use srt counter but declared as static const str wriiteen while writing any header
4) Removed srt counter from output file from webvtt refrence taken from http://dev.w3.org/html5/webvtt/
=> refactor Webvtt

src/gpacmp4/box_code_base.c
=> Avoid derefrence of NULL

src/lib_ccx/asf_functions.c, src/lib_ccx/avc_functions.c, src/lib_ccx/avc_functions.h, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_decoders_isdb.c, src/lib_ccx/ccx_decoders_isdb.h, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/es_functions.c, src/lib_ccx/file_buffer.h, src/lib_ccx/file_functions.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/list.h, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_functions.h, src/lib_ccx/ts_info.c, src/lib_ccx/ts_tables.c, src/lib_ccx/utility.h, windows/ccextractor.vcxproj, windows/ccextractor.vcxproj.filters
=> ISDB support

docs/CHANGES.TXT
=> Update isdb changes

src/lib_ccx/ccx_decoders_608.c, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_isdb.c, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ts_functions.c
=> strtok_r for windows

src/lib_ccx/ts_functions.c
This was skipped unknowingly while making multi program PCR code.
Also fixes #237
=> putting back logic of skiping packet when empty

src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/params.c, src/lib_ccx/utility.c
=> Adding simple xml support

src/ccextractor.c, src/lib_ccx/ccx_common_common.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/params.c, src/lib_ccx/stream_functions.c, src/lib_ccx/telxcc.c
=> Remove seg-fault at invalid mp4 detection

docs/CHANGES.TXT, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_common.h, src/lib_ccx/ccx_encoders_g608.c, src/lib_ccx/params.c, src/lib_ccx/utility.c
=> Added g608 support

docs/CHANGES.TXT
=> updated CHANGE for bugs resolved

docs/CHANGES.TXT, src/lib_ccx/ccx_common_option.h, src/lib_ccx/lib_ccx.h, src/lib_ccx/params.c, src/lib_ccx/telxcc.c
=> Added --nohtmlescape

docs/CHANGES.TXT, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/es_userdata.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/params.c
=> Added --noscte20 close #244

src/lib_ccx/avc_functions.c
=> error check before file open

src/zvbi/bcd.h, src/zvbi/decoder.c, src/zvbi/misc.h, src/zvbi/zvbi_decoder.h, windows/ccextractor.vcxproj, windows/ccextractor.vcxproj.filters
=> make code windows compatible

.gitignore, src/CMakeLists.txt
Test pass under Ubuntu 14.04. Cmake3.0.2
=> Fix CMakeLists.txt

src/lib_ccx/es_userdata.c
Fixes #274, introduced in the commit mentioned above when a call to read_bits was commented out.
=> Fix issue #274, caused by commit 8d073accd4cfa

src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_decoders_608.c, src/lib_ccx/ccx_encoders_helpers.c, src/lib_ccx/es_userdata.c
Geocities shut down, docs moved to http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/SCC_TOOLS.HTML
=> Fixing broken links to McPoodle's docs

src/lib_ccx/ccx_encoders_common.c
Fix for issue #282.
Timestamps are now correct
=> Fixing broken end timestamp in -ucla

src/ccextractor.c, src/lib_ccx/file_functions.c
Referring Issue #270, as mentioned by @worksflowguy, a detailed opening file error message is requested.
=> Referring Issue #270. Detailed opening file error message

windows/ccextractor.vcxproj, windows/ccextractor.vcxproj.filters
Fixes windows build by adding zvbi include.
=> Fix windows build

src/ccextractor.c, src/lib_ccx/avc_functions.c, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/es_userdata.c, src/lib_ccx/general_loop.c, src/lib_ccx/params.c
A few commented lines exist. Will uncomment once @anshul1912 responds.
=> Fixes issue #285. Added Previews in GUI and statistics which were missing after refactoring.

docs/CHANGES.TXT, src/ccextractor.c, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_common.h, src/lib_ccx/ccx_encoders_structs.h, src/lib_ccx/lib_ccx.h, src/lib_ccx/output.c, src/lib_ccx/params.c, src/lib_ccx/utility.c, src/lib_ccx/utility.h
**FinalPull** request. Memory issues solved
Referencing #345
=> File rotation feature and --append parameter

src/gpacmp4/box_funcs.c
=> mp4 void atoms fix

src/lib_ccx/ocr.c, src/lib_ccx/spupng_encoder.c
=> Fixing missing lines in spupng

src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/ocr.c, src/lib_ccx/spupng_encoder.c, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_functions.h
correct Incorrect progress display
close #397
=> corrrect Incorrect progress display

.gitignore, linux/Makefile, linux/build, linux/builddebug, linux/pre-build.sh, mac/build.command, mac/pre-build.sh, src/lib_ccx/compile_info.h, windows/ccextractor.vcxproj, windows/pre-build.bat
As discussed with @anshul1912, currently the git-ignore is ignoring the already commited file. By moving the dynamic file creation to a separate file, this problem is resolved.
=> Version fix

src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/ocr.c, src/lib_ccx/ocr.h, src/lib_ccx/params.c
Detects and outputs word-wise color and the point of speaker changes in DVB subtitles. Outputs font tags to SRT and WebVTT.
=> DVB Color Detection

src/ccextractor.c, src/lib_ccx/avc_functions.h, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_decoders_structs.h, src/lib_ccx/list.h, src/lib_ccx/myth.c, src/lib_ccx/networking.c, src/lib_ccx/ocr.c, src/lib_ccx/stream_functions.c, src/lib_ccx/telxcc.c, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_tables.c, src/lib_ccx/ts_tables_epg.c, src/lib_ccx/wtv_constants.h, src/lib_ccx/wtv_functions.c
=> Various spelling corrections.

README.md
This is for the Modify README.MD Task
Thanks to the Mentors
=> Google Code In 2016 Modify README.MD

windows/ccextractor.vcxproj
Regular debug & release have a missing folder
=> Add utf8proc folder to the include directories

Dictionary/dict_Arrow.txt, Dictionary/dict_Breaking_Bad.txt, Dictionary/dict_Game_of_Thrones.txt, Dictionary/dict_House.txt
Used a python script to generate all characters automatically just with the help of IMDB ID. This task was listed in GCI16. I have uploaded the files even in the GCI website. Please review and respond. Thanks 👍
=> Added 4 TV series database as requested.

Dictionary/dict_greys.anatomy.txt, Dictionary/dict_mr_robot.txt, Dictionary/dict_the.big.bang.theory.txt, docs/CHANGES.TXT, docs/FFMPEG.TXT, docs/FRONTEND_COMMUNICATIONS.TXT, docs/G608.TXT, docs/HARDSUBX.txt, docs/MAILINGLIST.TXT, docs/OCR.txt, docs/using_cmake_build.txt, src/ccextractor.c
Fixed multiple spelling errors and added characters to Show Dictionaries.
=> Fixes for Code-in Task

linux/Makefile, linux/build_hardsubx, raspberrypi.md
I fixed the Makefile compatibility issues with Raspberry Pi along with adding utf8proc to actually be compiled.
=> Generate official files for Raspberry Pi

src/lib_ccx/ccx_encoders_ssa.c
Added functions to write subs. Other encoders were very helpful.
=> Added two functions for ASS/SSA encoder

README.md
Updated the README.md as one of the tasks for the Google Code-in. I reorganized some of the sections of the README.md, provided more links to website documentation, added information about support, and patched up some of the grammar.
=> GCI: Updated README.md

README.md
Removed a redundant line - "You can also".
=> Minor correction in README.md

src/CMakeLists.txt
Added strings for building in CLion
=> Fixed CMakeLists for build in cmake

src/lib_ccx/ccx_demuxer.c
Description and discussion here : https://github.com/CCExtractor/ccextractor/pull/529
=> Printing exact error for clean file.

linux/Makefile
There was a missing directory /src/protobuf-c in makefile for linux installation.
=> Fixed missing directory in Makefile for linux.

linux/build
=> Fixed linux/build script - checking for dependencies

docs/README.TXT
Added Manveer Basra to `README.TXT` under `Google Code-in 2016 students`
=> Added Manveer Basra to README.TXT

linux/description-pak, package_creators/debian.sh
(sorry for non-english)
This command build the .deb file in folder package_creators/build, and you can install by:
```
sudo dpkg -i %built_filename%.deb
sudo apt-get -y -f install
```
(Last command for dependencies)
And then you can run `ccextractor` in console in any folder of your system.
=> Added build script for .deb

src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_smptett.c
Fix to : https://github.com/CCExtractor/ccextractor/issues/380
More description in individual commits and in the code comments. :)
=> Adobe Premiere Pro Compatibility.

README.md
=> The proposal to update the "Compiling" section

src/lib_ccx/ccx_encoders_smptett.c
Also polished and improved existing code. More details : CCExtractor#620
=> SMPTE-TT : Removed appearance of garbage value in color code.

src/lib_ccx/ccx_decoders_708.c
=> Fixes #618

src/lib_ccx/ccx_decoders_xds.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/myth.c, src/lib_ccx/networking.c, src/lib_ccx/spupng_encoder.c, src/lib_ccx/ts_tables_epg.c
=> Fix defects

src/lib_ccx/ocr.c
Closes https://github.com/CCExtractor/ccextractor/issues/448
=> Check for language tesseract data in /usr/share/tessdata/

src/lib_ccx/ccx_decoders_708.c, src/lib_ccx/ccx_decoders_708.h, src/lib_ccx/ccx_decoders_708_output.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_common.h, src/lib_ccx/general_loop.c
Descriptions in the names of commits
=> CEA-708 improvements

src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_decoders_common.h, src/lib_ccx/ccx_decoders_vbi.h, src/lib_ccx/ccx_decoders_xds.c, src/lib_ccx/ccx_decoders_xds.h, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_tables.c
- Fixed multiprogram for DVB and Teletext
- Huge code refactoring regarding min_pts calculation
- Fixed DVB memory leak (Closes #639)
- Code cleanup
=> Fixed DVB multiprogram

src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer.h, src/lib_ccx/ts_functions.c, src/lib_ccx/ts_tables.c
- Avoided lots of loop iterations when calculating the min_pts
=> Sped up min_pts calculation 

src/ccextractor.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/params.c, src/lib_ccx/utility.c
=> Changes regarding output file name and minor print_usage corrections.

README.md
Tested on my host computer and virtual box
=> Updated "Compiling" section with Fedora

src/lib_ccx/ccx_decoders_708_output.c
Previously, I wrote down all the characters at once, but it gave rise to different encoder errors. It's better (and faster I guess) to save all chars in the buffer at print the whole buffer.
Closes #690
=> Rewritten output handler

src/lib_ccx/general_loop.c
Apparently, Teletext has to be in sync with Private Stream 1 (before, it was in sync with ALL streams).
( Closes #695 )
=> Sync Teletext to Private Stream 1 instead of all streams

src/lib_ccx/ccx_encoders_transcript.c
This PR is unfinished and may be even incorrect. I needed to use sample platform to test the changes hence this PR, please don't close it.
=> [WIP] Fixed missing tpage number in UCLA from BIN.

src/lib_ccx/matroska.c
In regard with point 3 https://github.com/CCExtractor/ccextractor/issues/705
=>  	modified subtitle file name genrated by matroska(mkv) - remove 'mkv'

src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/matroska.c, src/lib_ccx/matroska.h, src/lib_ccx/params.c
---
fixes points 1,2,4 and additional `-mklang` option mentioned in #705
=> **[FIX]** Fixes issue #705

src/lib_ccx/ccx_encoders_common.c
=> [FIX] # 680 Add missing line terminator in webvtt

src/lib_ccx/matroska.c, src/lib_ccx/matroska.h, src/lib_ccx/utility.c, windows/ccextractor.vcxproj
**In raising this pull request, I confirm the following:**
**My familiarity with the project is as follows:**
---
This pull request implements extraction of WebVTT subtitles from Matroska files. I am hoping to earn 5 GSOC qualification points from this pull request.
I have tested this code with the sample video in issue #724 and the output appears to be correct. However, I have not been able to find other applicable test cases for this code (mkv files with WebVTT subtitles). Also, all of my testing was done on a 64-bit Windows machine.
=> [FEATURE] Add WebVTT output from Matroska (Issue #724)

src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.c, src/lib_ccx/telxcc.c
- [*] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [*] I have checked that another pull request for this purpose does not exist.
- [*] I have considered, and confirmed that this submission will be valuable to others.
- [*] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [*] I give this submission freely, and claim no ownership to its content.
- [*] I absolutely love CCExtractor, but have not …
=> Issue 699 solved

.gitignore, README.md, docs/CHANGES.TXT, package_creators/ccextractor.spec, package_creators/rpm.sh
---
Added script to generate .rpm package.
Solves a part of issue #678
=> [FEATURE]Add .rpm package generation script

.gitignore, README.md, docs/CHANGES.TXT, mac/Makefile.am, mac/autogen.sh, mac/build.command, mac/cleanup, mac/configure.ac
---
For ocr and hardsubx to work on mac:
Install `pkg-config`
Install `autoconf` tools
Install `tesseract` and `leptonica` (make sure they are detected by `pkg-config`)
Install `ffmpeg` (make sure `avutil`,`avformat`, etc are detected by `pkg-config`)
Change to `mac` dir in `ccextractor`
run `./autogen.sh`
run `./configure --enable-ocr --enable-hardsubx`
run `make`
Solves issue #727
=> [IMPROVEMENT]Add ocr, hardsubx and autotools support for mac

docs/OCR.txt
=> Adding info for ocr

.gitignore, src/CMakeLists.txt
---
CMake now works successfully on Windows.
- added missing libraries
- fixed broken linker flags
=> [Fix][IMPROVEMENT] CMake build for windows.

src/gpacmp4/mp4.c, src/lib_ccx/ccx_encoders_webvtt.c
=> [FIX] Initialise timing for MP4 webvtt.

README.md, src/lib_ccx/asf_functions.c, src/lib_ccx/ccx_encoders_transcript.c
=> [FIX] - Fixing end timestamp in DVB transcripts + spelling/readme improvements

api/api_testing.py, api/build_api, api/build_library, api/ccextractor.py, api/ccextractor_wrap.c, linux/build, src/ccextractor.c, src/ccextractor.h, src/lib_ccx/ccx_decoders_708_output.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_g608.c, src/lib_ccx/ccx_encoders_sami.c, src/lib_ccx/ccx_encoders_smptett.c, src/lib_ccx/ccx_encoders_srt.c, src/lib_ccx/ccx_encoders_ssa.c, src/lib_ccx/ccx_encoders_transcript.c, src/lib_ccx/ccx_encoders_webvtt.c, src/lib_ccx/matroska.c
---
This pull request mainly comprises a feature of accessing the extracted captions in python. This has been accomplished by using a wrapper for the standard `write` function.
=> **[FEATURE]**: Extracted captions in python

api/api_testing.py, api/build_api, api/ccextractor.i, api/ccextractor.py, api/ccextractor_wrap.c, api/wrappers/wrapper.c, api/wrappers/wrapper.h
- [*] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [*] I have checked that another pull request for this purpose does not exist.
- [*] I have considered, and confirmed that this submission will be valuable to others.
- [*] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [*] I give this submission freely, and claim no ownership to its content.
- [*] I am an active contributor to CCExtractor.
---
This …
=> [FEATURE] Compile param wrappers for python

src/lib_ccx/matroska.c
---
Added gui mode reports for Matroska decoder
=> **[IMPROVEMENT]** Added gui mode reports for Matroska decoder

docs/Python extension module.txt, docs/README.TXT
- [*] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [*] I have checked that another pull request for this purpose does not exist.
- [*] I have considered, and confirmed that this submission will be valuable to others.
- [*] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [*] I give this submission freely, and claim no ownership to its content.
- [*] I am an active contributor to CCExtractor.
---
This …
=> Python Extension Module 

.gitignore, windows/ccextractor.vcxproj
---
- Fixed Windows project files causing an "xcopy (...) exited with code 4" error.
=> [FIX] Fix Windows project files

README.md, mac/README.MAC.TXT, mac/build.command, src/CMakeLists.txt
---
This is in reference to issue #776.
=> Compilation on the Mac

docs/guidoc.md
---
Added documentation for GUI added in #794
=> [IMPROVEMENT]Add documentation for GUI

src/extractors/extractor.c
Fixes https://github.com/CCExtractor/ccextractor/issues/780
Signed-off-by: Saksham Gupta <shucon01@gmail.com>
---
=> Fixes Undeclared-Variable Warnings in extractor.c

src/ccextractor.c, src/ccextractor.h, src/extractors/extractor.c, src/extractors/extractor.h, src/lib_ccx/ccx_common_option.c, src/lib_ccx/ccx_common_option.h, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/output.c, src/lib_ccx/params.c, src/wrappers/wrapper.c, src/wrappers/wrapper.h
Temporarily wrapped the Python API in order to prevent errors in the program.
=> Temporarily wrapped the Python API

src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_encoders_python.c, src/lib_ccx/ts_tables.c
---
This replaces some wrong memsets with traditional for loops.
=> [FIX] Replace incorrect memset

docs/README.TXT
---
You forgot me :( and another finalist
=> More Google Code In Participants

Dictionary/dict_mr_robot.txt
=> [IMPROVEMENT]Update dict_mr_robot.txt

src/ccextractor.c, src/lib_ccx/asf_functions.c, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/es_functions.c, src/lib_ccx/myth.c, src/lib_ccx/networking.c, src/lib_ccx/params.c, src/lib_ccx/ts_functions.c
=> Making error messages clearer and less ambiguous.

src/zlib/adler32.c, src/zlib/compress.c, src/zlib/crc32.c, src/zlib/deflate.c, src/zlib/deflate.h, src/zlib/gzguts.h, src/zlib/gzlib.c, src/zlib/gzread.c, src/zlib/gzwrite.c, src/zlib/infback.c, src/zlib/inffast.c, src/zlib/inflate.c, src/zlib/inflate.h, src/zlib/inftrees.c, src/zlib/trees.c, src/zlib/uncompr.c, src/zlib/zconf.h, src/zlib/zlib.h, src/zlib/zutil.c, src/zlib/zutil.h
=> [IMPROVEMENT] Upgrade zlib to 1.2.11

src/win_iconv/iconv.h, src/win_iconv/win_iconv.c
---
Upgrade win_iconv to its least version (master branch 18 Mar 2016)
=> [IMPROVEMENT] Upgrade win_iconv

src/lib_ccx/ccx_encoders_srt.c
---
Fix delay option (issue #779 )
=> [FIX] Fix delay option

src/ccextractor.c, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/ccx_demuxer.c, src/lib_ccx/ccx_demuxer_mxf.c, src/lib_ccx/ccx_demuxer_mxf.h, src/lib_ccx/file_buffer.h, src/lib_ccx/file_functions.c, src/lib_ccx/general_loop.c, src/lib_ccx/lib_ccx.h, src/lib_ccx/stream_functions.c, src/lib_ccx/utility.c, src/lib_ccx/utility.h, windows/ccextractor.vcxproj
- [Y ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ Y] I have checked that another pull request for this purpose does not exist.
- [ Y] I have considered, and confirmed that this submission will be valuable to others.
- [ Y] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ Y] I give this submission freely, and claim no ownership to its content.
- [N ] I have never used CCExtractor.
- [ N] I have …
=> Add MXF support

src/lib_ccx/ccx_encoders_srt.c
pr
---
Fix -delay option in DVB
=> Fix -delay option in DVB

.travis.yml
---
I fixed one of the builds for Travis and now Tesseract and Leptonica are installed
=> [FIX] Add leptonica and tesseract

README.md, docs/COMPILATION.MD
---
I've tried to improve the README a little
=> [IMPROVEMENT]Improve README a little

src/CMakeLists.txt, src/lib_ccx/CMakeLists.txt
---
Make CMakeFiles work with Windows Visual Studio
Fix #812
=> [FIX] Make CMakeFiles work with Windows Visual Studio

README.md
---
Part of GCI task
Added and fix some things
Thanks
=> Added Supports and replace some things

src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/ocr.c
=> [FIX] Fix a crash while processing DVB subtitles

src/lib_ccx/dvb_subtitle_decoder.c
---
Fix #279 by merging all regions into one before passing to OCR
It works for the sample but not sure if it will affect anything else. (See the code for detail)
I'd wait for the result of the sample platform.
=> [Fix] Fix OCR issue caused by separated dvb subtitle regions

src/lib_ccx/dvb_subtitle_decoder.c
---
Fix dvb subtitle not extracted if there's no display segment.
This fixes part of #243 (Cine Clan TVE  Perez, el ratoncito de tus sueÃ±os 2.ts)
=> [FIX] Fix dvb subtitle not extracted if there's no display segment

src/gpacmp4/base_encoding.c, src/gpacmp4/bitstream.c, src/gpacmp4/configfile.c, src/gpacmp4/data_map.c, src/gpacmp4/desc_private.c, src/gpacmp4/error.c, src/gpacmp4/gpac/avparse.h, src/gpacmp4/gpac/base_coding.h, src/gpacmp4/gpac/bitstream.h, src/gpacmp4/gpac/constants.h, src/gpacmp4/gpac/events_constants.h, src/gpacmp4/gpac/ietf.h, src/gpacmp4/gpac/internal/avilib.h, src/gpacmp4/gpac/internal/odf_dev.h, src/gpacmp4/gpac/internal/odf_parse_common.h, src/gpacmp4/gpac/internal/ogg.h, src/gpacmp4/gpac/mpeg4_odf.h, src/gpacmp4/gpac/network.h, src/gpacmp4/gpac/sync_layer.h, src/gpacmp4/gpac/tools.h, src/gpacmp4/gpac/utf.h, src/gpacmp4/gpac_ogg.c, src/gpacmp4/list.c, src/gpacmp4/media_odf.c, src/gpacmp4/odf_codec.c, src/gpacmp4/odf_command.c, src/gpacmp4/os_divers.c, src/gpacmp4/slc.c, src/gpacmp4/stbl_read.c
---
Whitespace changes only, there are small changes but I'm sure that would be valid.
=> {IMPROVEMENT] Whitespace changes (Part of libGPAC update)

docs/COMPILATION.MD
Added uniformity with respect to CMake
---
=> [IMPROVEMENT] Minor typographical fix

README.md
Documentation: Write a better README for our GitHub page
---
=> [IMPROVEMENT] New README for GCI

.github/CONTRIBUTING.md
Original link no longer exists; replaced with User link
---
=> Change contributor guide link

docs/README.TXT
=> [IMPROVEMENT] Add Google Code In 2017 Participants

src/lib_ccx/ccx_encoders_common.h
---
This will fix #901 -- Compilation errors when using CMake.
Sorry that I introduced this issue.
=> [FIX] Fix compilation error in CMake

src/lib_ccx/ccx_encoders_spupng.c
---
The path in generated XML (spupng) was always `sub0000.png`. This patch fixs it.
=> [FIX] Fix incorrect path in XML (spupng)

.gitignore, docs/ccextractor.cnf.sample
---
Updated .gitignore file with the files to be ignored made by CMake installation.
=> [IMPROVEMENT] Update .gitignore

README.md
=> [IMPROVEMENT] Display Sample-Platform Build Badges on README

README.md
Review whenever convenient :)
---
=> [IMPROVEMENT] Added SourceForge Downloads Badge

src/gpacmp4/mp4.c
---
Fix a minor spelling error in mp4.c
``Rrocess`` --> ``Process``.
=> [FIX] Fix a minor spelling error in mp4.c

.gitignore, api/api_support.py, api/api_testing.py, api/ccx_to_python_g608.py, api/python_srt_generator.py, api/recursive_tester.py, tools/histogram.py
---
Using the futurize library, the present python scripts of CCExtractor has been made compatible for Python 3 and Python 2 both. The minor changes introduced have been manually looked into for errors since I couldn't find a way to test them. 
Also, the SWIG wrapping scripts have been checked to wrap for Python 3 with backward compatibility to python 2.
Implements #912
=> [IMPROVEMENT] Code made compatible with Python 3

README.md, src/lib_ccx/params.c
---
#936 
Following libraries don't have any way to print their version numbers, so I just printed their names.
- zvbi
- nuklear
- libhash
FreeType has these macros FREETYPE_MAJOR, FREETYPE_MINOR, FREETYPE_PATCH which can be used, but it is throwing some errors which I was not able to fix.
=> [FEATURE] Added version no. of libraries to --version

.travis.yml
---
- Updated traivis.yml to fix osx build crash.
=> [FIX] Updated traivis.yml to fix osx build

docs/COMPILATION.MD
---
Add instructions to make the installation systemwide (on Linux) which can allow CCExtractor to be used from anywhere with just the below command in terminal:
`ccextractor [videofile]`
=> [IMPROVEMENT] Update COMPILATION.md

src/lib_ccx/dvb_subtitle_decoder.c
Please prefix your pull request with one of the following:
---
Thank you very much, @thealphadollar, for inviting me to submit a pull request to fix the problem with the colors of dvb subtitles with depth 2!
This pull request fixes the problem for me; I hope it's correct.
Kind regards,
Andreas Trottmann
=> [FIX] added missing break statement

README.md
Replaced old logo with the new one.
---
=> [IMPROVEMENT] Update Logo

src/lib_ccx/hardsubx.c, src/lib_ccx/hardsubx.h, src/lib_ccx/hardsubx_decoder.c
- [] I have never used CCExtractor.
- [] I have used CCExtractor just a couple of times.
- [] I absolutely love CCExtractor, but have not contributed previously.
---
Fixed some minor memory leaks, some typographical errors and added some missing declarations.
=> [FIX] Fix some minor memory leaks

README.md
=> [IMPROVEMENT] Add GCI 2018 info (remove GSoC 2018)

README.md
---
- Corrected and improved text
- Added link to GCI post on ccextractor website.
=> [IMPROVEMENT] Add GCI banner and change text.

README.md
=> [IMPROVEMENT] Add downloads badge for v0.87

docs/CHANGES.TXT, src/lib_ccx/general_loop.c
=> [FIX] Fixed /dev/null bug

docs/CHANGES.TXT, src/ccextractor.c
=> [FIX] Fixed a minor reportng stats bug 

docs/CHANGES.TXT, src/lib_ccx/ccx_decoders_common.c, src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_common.h, src/lib_ccx/ccx_encoders_srt.c, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/matroska.c, src/lib_ccx/matroska.h
---
Added support for extracting DVB subtitles from MKV files. Solves #1000
=> [FEATURE] Added support for DVB inside MKV

README.md
And link to latest release. Earlier it was for a specific release instead of the cumulative download count spanning all releases.
---
=> [IMPROVEMENT] Update badge with total download count

docs/CHANGES.TXT, linux/Makefile.am
- [ x] I have checked that another pull request for this purpose does not exist.
- [x ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
- [x ] I absolutely …
=> **[FIX]** Enable RPM creation to work correctly

docs/CHANGES.TXT
=> Fix for #1115

src/lib_ccx/ccx_encoders_webvtt.c
---
Fixed the X-TIMESTAMP-MAP formatting error. Made required changes as mentioned in the issue #1125
=> [FIX] Fixed X-TIMESTAMP-MAP formatting error

src/lib_ccx/ccx_encoders_helpers.c
=> [IMPROVEMENT] Fix typo

src/ccextractor.c, src/lib_ccx/ccx_encoders_webvtt.c
=> [FIX] Make header respect `-lf` for the webvtt encoder

docs/CHANGES.TXT, src/lib_ccx/cc_bitstream.c
=> [FIX] Hang while processing video #1121

docs/CHANGES.TXT, src/lib_ccx/ccx_common_constants.h, src/lib_ccx/params.c
=> [IMPROVEMENT] Add fatals to params without args

docs/COMPILATION.MD
=> [IMPROVEMENT] Mention -DWITH_OCR in compilation instruction

src/lib_ccx/networking.c
=> [FIX] Used the INET_ADDRSTRLEN constant for network functions

src/lib_ccx/ocr.c
---
Addresses https://github.com/CCExtractor/ccextractor/pull/402#discussion_r368041348
=> Fix memory leak

src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/lib_ccx.c
=> [FIX] Fix segfault

.github/workflows/build_linux.yml
=> [IMPROVEMENT] Add Cmake job to github action

src/lib_ccx/ccx_common_option.h, src/lib_ccx/hardsubx.c, src/lib_ccx/matroska.h, src/lib_ccx/ocr.c, src/lib_ccx/ocr.h, src/lib_ccx/params.c, src/lib_ccx/utility.h
---
Fixes what was discussed in #1161 about `-ocrlang` not working.
@hamelg
=> [FIX] Make `-ocrlang` work

.github/workflows/build_linux.yml
=> [IMPROVEMENT] Test with OCR and HARDSUBX

src/lib_ccx/ccx_encoders_common.c, src/lib_ccx/ccx_encoders_scc.c
=> [IMPROVEMENT] [SCC/CCD encoder] Allow the user the choose between CRLF and LF

docs/CHANGES.TXT, mac/pre-build.sh
=> [FIX] Fix Mac build error for reproducible builds

.github/ISSUE_TEMPLATE.md
=> Mention where to send private invitation in the ISSUE_TEMPLATE

.github/workflows/build_windows.yml
---
Another small step to improve the usability of the generated artifacts.
=> Add DLL's to artifact

src/lib_ccx/ccx_common_option.c
=> [FIX] [Formatting] Remove trailing whitespace

src/lib_ccx/ocr.c
=> Created block of code for single line branches at lines between 660-670.

docs/COMPILATION.MD
**[IMPROVEMENT]**
---
**Fixed a grammatical error in Compilation Guide (COMPILATION.MD).**
=> Documentation fix

.github/workflows/build_linux.yml, .github/workflows/build_windows.yml
**[FIX]**
---
Fix #1284
Updated GitHub actions from v1 to v2 where ever necessary.
Reduced the number of steps required to upload an artifact [Windows].
=> Updated Github actions and reduced steps required to upload artifacts.

src/lib_ccx/stream_functions.c
---
Added brackets for single line `if` blocks in [`stream_functions.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/stream_functions.c)
Btw the [getting start page](https://www.ccextractor.org/public:general:gettingstartedwithourcode) of CCExtractor is amazing!! <3<3 for the people who put their efforts.
=> added brackets for single line if statements

src/lib_ccx/ccx_encoders_mcc.c
=> [FIX] Remove -Wimplicit-function-declaration warning #1296

README.md
---
**Changes**
- Fixed a typo where the word "website" was repeated two times in the top-level README.md file.
=> [DOCUMENTATION] : Fixed a typo

src/lib_ccx/ccx_encoders_common.h, src/lib_ccx/ts_tables_epg.c
---
Add thirdparty to win_iconv path
=> Update win_iconv path

.github/workflows/build_linux.yml, .github/workflows/format.yml, docs/COMPILATION.MD, docs/using_cmake_build.txt
---
Add build and format CI for rust code
Add docs on how to compile rust code
Merge only after #1351 is merged
=> Add CI and docs for rust lib

src/lib_ccx/ccx_decoders_708.c, src/lib_ccx/ccx_decoders_708.h, src/rust/src/decoder/commands.rs, src/rust/src/decoder/mod.rs
---
Add process current packet and process service decoders functions to rust
=> Add functions to rust

src/lib_ccx/ccx_decoders_708.c, src/rust/src/decoder/mod.rs, src/rust/src/decoder/service_decoder.rs, src/rust/src/decoder/timing.rs, src/rust/src/decoder/window.rs, src/rust/src/lib.rs
---
Add Pen Presets and timing functions
=> [rust] Add Pen Presets and timing functions

src/rust/src/decoder/mod.rs, src/rust/src/decoder/service_decoder.rs, src/rust/src/decoder/tv_screen.rs, src/rust/src/decoder/window.rs
Add tv_screen module, copy to screen and other functions
=> Rust updates

.github/ISSUE_TEMPLATE.md
=> Add comment to create GUI issues in GUI repo

src/lib_ccx/ccx_decoders_common.c, src/rust/src/decoder/commands.rs, src/rust/src/decoder/mod.rs, src/rust/src/decoder/output.rs, src/rust/src/decoder/service_decoder.rs, src/rust/src/decoder/timing.rs, src/rust/src/decoder/tv_screen.rs, src/rust/src/decoder/window.rs, src/rust/src/lib.rs
Update rust code documentation
=> Rust updates:- Update documentation

src/lib_ccx/ccx_encoders_common.c, src/rust/CMakeLists.txt, windows/rust.bat, windows/rustx86.bat
Fix for #1389 and some miscellaneous changes
=> Fix negative delay bug, and other miscellaneous changes

.github/workflows/build_windows.yml, docs/CHANGES.TXT, docs/COMPILATION.MD, windows/ccextractor.vcxproj
=> Update windows build

src/lib_ccx/ccx_decoders_708.c, src/rust/src/decoder/service_decoder.rs
Print subtitles only if roll-up is enabled
=> Fix Carriage Return command

src/lib_ccx/dvb_subtitle_decoder.c
=> Check start/end at param before encoding DVB subs

src/lib_ccx/matroska.c, src/lib_ccx/matroska.h, src/lib_ccx/stream_functions.c
Fix file extension for `idx` and add VOBSUB unsupported message
#1371
=> Fix file extension for IDX files

src/lib_ccx/hardsubx_classifier.c, src/lib_ccx/hardsubx_decoder.c, src/rust/Cargo.lock, src/rust/Cargo.toml, src/rust/build.rs, src/rust/src/hardsubx/classifier.rs, src/rust/src/hardsubx/decoder.rs, src/rust/src/hardsubx/mod.rs, src/rust/src/utils.rs, src/rust/wrapper.h
Starting port of the classifier module.
=> [WIP] Port hardsubx classifier

docs/COMPILATION.MD
---
`docs/COMPILATION.md` was missing the instructions to install the dependencies for Arch Linux. I also did some minor formatting fixes.
=> [IMPROVEMENT] Adding Arch Linux instructions and other minor fixes to COMPILATION.MD

docs/COMPILATION.MD, docs/FFMPEG.md
---
Windows build has been updated to vcpkg, so the docs needed an update too...
=> [IMPROVEMENT] Update documentation for windows build

docs/COMPILATION.MD
Added the 2 necessary env vars required to compile hardsubx now
=> Update compilation docs for hardsubx

src/lib_ccx/ocr.c
---
This PR is the suggested fix to the infamous OCR noise problem in issue #929 
I've checked the discussion there and found that the last step that hasn't been implemented is the erosion-dilation to remove the noise surrounding the text after using the built-in `quantize_map` function.
I've spent the last two days decrypting the `quantize_map` function, partly because of how weird the png format stores the color palette and bitmap seperately and partly because the function output doesn't respect it's input parameters. i.e: when passing the `max_color=3` to the function, it actually outputs an image with only 2 colors, one of which is …
=> [IMPROVEMENT] add erosion then dilation after quantization

src/ccextractor.c, src/lib_ccx/ccx_decoders_708.c, src/lib_ccx/ccx_decoders_isdb.c, src/lib_ccx/ccx_encoders_g608.c, src/lib_ccx/dvb_subtitle_decoder.c, src/lib_ccx/sequencing.c
=> [FIX] Apply formatting (again)

.github/workflows/build_windows.yml
=> [FIX] update vcpkg ref

docs/CHANGES.TXT, src/lib_ccx/ccx_common_common.h, src/lib_ccx/ccx_common_constants.h
---
Provide unique values to enums
=> [FIX] Repeated values for enums

.github/workflows/build_windows.yml, docs/COMPILATION.MD, docs/FFMPEG.md, windows/ccextractor.vcxproj
---
Fix Build and link dll's statically
=> [FIX] Update Windows build

docs/COMPILATION.MD
=> [FIX] Add gpac-devel dependency for RHEL/Fedora

.github/workflows/build_windows.yml, windows/.gitignore, windows/ccextractor.vcxproj, windows/ccextractor.vcxproj.filters, windows/vcpkg.json
---
Windows CI was broken due to not pinning of dependencies
=> [FIX (Windows)] CI build
