- src/ccextractor.c
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/output.c
This is the fix for SegFault errors occurring while the output format was set to .bin/.raw format
Issue Link:https://github.com/CCExtractor/ccextractor/issues/102
> Fix for SegFault error in -out=raw/bin output format

- src/ccextractor.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/params.c
Terminating application if one of output filenames is same as one of input filenames. Since it looks like user has mistaken with input or output parameters, I decided that this error is fatal and there is no need to try to handle this situation in ccextractor (e.g. add something to the output name).
> Prevent overwriting files

- src/lib_ccx/stream_functions.c
This fix is based on gpacs' mp4 detecition "gf_isom_probe_file" function
there was a typo in mp4 detection algorithm 'feee'->'free'
I had also added 'wide' box to mp4 detection algorithm, because it could also appear in the beginning of the file
I haven't found any description of 'jP  ' box, so it was not included in this fix
Hope this fix will slightly increase true positive rate of mp4 detection.
> Attempt to improve mp4 detection

- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/stream_functions.c
- src/lib_ccx/ts_functions.c
This handling is be better, because broken PES packets could happen too.
> handling 7-byte PES packets for dvb-subs stream

- docs/CHANGES.TXT
- src/lib_ccx/stream_functions.c
Regression testing points out that at least 12 files no longer produce
correct results due to this change. Reverting is necessary until a
better solution for #69 can be found that does not break current other
files.
> Revert of changes in stream format detection

- src/lib_ccx/lib_ccx.h
- src/lib_ccx/stream_functions.c
Expanded detection for mp4. This fix does not affect any other files (as opposed to the initial "fix").
New detection code requires a couple of valid mp4 boxes after each other instead of just a single string reference. It uses the length parameter of the supposed mp4 boxes to skip the contents of the supposed boxes (as would be the case in mp4).
> Possible MP4 detection fix

- src/ccextractor.c
- src/gpacmp4/mp4.c
- src/lib_ccx/608_sami.c
- src/lib_ccx/608_smptett.c
- src/lib_ccx/608_srt.c
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_decoders_608.c
- src/lib_ccx/ccx_decoders_608.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_common.h
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_decoders_xds.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_mp4.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/networking.c
- src/lib_ccx/networking.h
- src/lib_ccx/output.c
- src/lib_ccx/params.c
- src/lib_ccx/telxcc.c
- src/lib_ccx/utility.c
now use of global options ccx_options left only in ts parser(PAT, PMT)
Tested pull request using Willem TestSuite.
> Removing use ccx_options from decoders and encoders

- src/CMakeLists.txt
Compilation via cmake fails on OS X if libiconv is not specified as a required library:
```
Undefined symbols for architecture x86_64:
"_iconv", referenced from:
_EPG_DVB_decode_string in libccx.a(ts_tables_epg.c.o)
"_iconv_close", referenced from:
_EPG_DVB_decode_string in libccx.a(ts_tables_epg.c.o)
"_iconv_open", referenced from:
_EPG_DVB_decode_string in libccx.a(ts_tables_epg.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Adding it to EXTRA_LIBS in CMakeLists.txt is enough to make compilation successful.
> Add iconv to EXTRA_LIBS in CMakeLists.

- src/lib_ccx/avc_functions.c
fixes espn.ts but affects /repository/newRepository/TestFiles/XDS/9.mpg which is already broken. (it seems that it extracts more data now http://gsocdev.ccextractor.org/~ruslan/tests/Testsuite_Report_2015-06-10_081012/Report__XDS_2015-06-10_081753.html )
> flushing cc buffer every I, P slice for both fields

- src/lib_ccx/lib_ccx.h
- src/lib_ccx/ts_tables_epg.c
Function definitons in output.c
Fixed in lib_ccx.h
> Fixing warning errors for GCC while compilation

- src/lib_ccx/ccx_decoders_708_output.c
%s argument added. Alternative would be using a different function instead of sprintf and change to strlcat. Then it has to be changed everywhere.
> Additional Argument added to sprintf giving the correct format specifier

- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/params.c
Added option for forcing a flush on the output buffer whenever content is written
> Added --forceflush (-ff) option

- src/lib_ccx/params.c
Fixes #326
Usage of -codec and -nocodec options at the end without any following option
gives 'Segmentation fault'.
Added checks to overcome this.
Signed-off-by: Neha Bagari <neha.bagari.eee11@iitbhu.ac.in>
> Check for number of args

- src/lib_ccx/params.c
Additional to #326 even, -outinterval throws a segfault. Fixed that by checking if it is the last argument.
> Fixed SegFaults while parsing parameters. Fixes issue #326

- src/lib_ccx/telxcc.c
This fixes all bugs regarding Latin G2 subsets and accented characters not displaying properly. Additionally the last string in buffer is also displayed properly now.
I've tested on all files and are working correctly.
> Bug fixes for Teletext files

- src/lib_ccx/telxcc.c
Fixes the issue #249 . 
Fixed according to X/26 packet specifications in ETS 300 706 v1.2.1 .
> Fix * displaying instead of @

- src/lib_ccx/stream_functions.c
File-detecting program detect only "mfra" mp4 box in this video which is a trailer and it is assigned weight 3 in ccx_stream_mp4_boxes . So, program detects file as mp4. "mfra" box weight should be "1" so that other box too can confirm file is mp4.
> "mfra" mp4 box weight changed to 1.Fix #273

- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_decoders_isdb.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/params.c
#284 
ISDB timestamps were not incrementing in some samples where the global timestamp was not initialized. In those cases, set the timestamp to the FTS.
Pull request #334 broke the output in valid files in which the global timestamp was correctly initialized. Fixed that in this one.
Also, this pull request takes care of removing the "NA" in the third column when using -UCLA.
> Fixing issues with ISDB

- src/lib_ccx/lib_ccx.c
#285 partial.
Fix for TARGET File is null. 
The other is part of the issue which can be easily solved according to me is based on the commented out part(#if 0) and renaming the variables. If it is fine, I will go ahead and check for the correct variables.
> Target file NULL fixed

- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_decoders_xds.c
- src/lib_ccx/ccx_decoders_xds.h
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/params.c
Fixes #347 
Always parsing XDS data. (ctx never initialized to null).
When using -xdsdebug, debug data always prints on screen but XDS data is written to file only in case of transcripts.
> Fixing problems with XDS

- src/lib_ccx/ccx_encoders_common.c
This fixes #359 the teletext page number being missing from the Red Hen output format
> Fix #359 - Teletext page number in -ucla

- src/lib_ccx/ccx_decoders_xds.c
Excessive aspect ratio XDS information does not get printed.
> Fixes #354 : Removes excessive XDS Notices

- .gitignore
- linux/Makefile
- linux/build
- linux/builddebug
- linux/pre-build.sh
- mac/build.command
- mac/pre-build.sh
- src/lib_ccx/compile_info.h
- src/lib_ccx/params.c
- src/lib_hash/README
- src/lib_hash/sha2.c
- src/lib_hash/sha2.h
- windows/ccextractor.vcxproj
- windows/ccextractor.vcxproj.filters
- windows/pre-build.bat
This PR adds the necessary functionality for a new --version option, as requested in #355.
* Adds a library for calculating SHA256 over the live running executable
* Adds a header file with the Git commit & build date
* Adds pre-build(.bat/.sh) script that creates the header file when called. This uses the current date and either one of `git rev-parse HEAD`, `.git/HEAD` or `.git/refs/master`  depending on availability. Defaults to "Unknown" if no .git directory is present.
* Updates the build scripts (and VS project) to include a call to the pre-build script before compilation starts
Closes #355.
> Add --version command

- docs/CHANGES.TXT
- src/lib_ccx/ccx_encoders_common.c
#360 had fixed the output for -ucla, but had broken normal ttxt output. This PR fixes both.
> Correcting display of teletext sub mode and info in transcripts

- src/lib_ccx/file_functions.c
Successor of the #323 PR. Instead of calling it every time when buffered_read_opt is called, it's now using a built in variable that holds the size already.
Closes #277, closes #281, closes #287
> Small input file fixes

- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/telxcc.c
Applying modified 'capitalize' and 'correct_case' functions for teletext with the same logic.
> Fixes #139 - Case fixing in teletext

- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/file_functions.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/ts_tables_epg.c
Fixes #353 
EPG variables were being initialized and taking up memory or around 180 MB while never being used. Fixed this by initializing them only when necessary.
Also includes a fix to passing the wrong context to the detect_myth() function, which was surprisingly still working with the live repository.
> Reducing Memory Consumption

- src/lib_ccx/params.c
- Removed unused variables
- Renamed remainder variables to better name
- Moved sha256_buf to external to avoid C4127 warning
> Fixing warnings

- src/lib_ccx/ocr.c
Fixing segfault for an empty line returned by Tesseract.
Also freeing color tables.
> Bug Fix for DVB Color

- src/lib_ccx/general_loop.c
Due to an assignment instead of comparison, all types of codecs handled
after the DVD subtitles would now be processed as DVD subtitles...
> Fix regression introduced in 1a1e973

- src/CMakeLists.txt
cmake build error in ubuntu16.10
1. Parse error.  Expected a command name, got unquoted argument with text "+".
2. ccx_encoders_splitbysentence.c:12:22: fatal error: utf8proc.h
3. params.c:830：undefined reference to‘SHA256_Init’
> fixed: cmake build error for ubuntu

- src/lib_ccx/ccx_encoders_common.h
Reordering definitions in the `ccx_encoders_common.h` to make it easier to read.
I just changed the order of definitions in .h file and added some spaces
> Cosmetic: Reordering definitions in the `ccx_encoders_common.h`

- src/lib_ccx/ccx_common_constants.h
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/params.c
- src/lib_ccx/utility.c
[https://codein.withgoogle.com/dashboard/task-instances/5110381871628288/](https://codein.withgoogle.com/dashboard/task-instances/5110381871628288/)
Added basic ASS/SSA encoding support.
I checked some files, works well. Run with args: `file -out=ssa` or `file -out=ass`.
`src/lib_ccx/ccx_encoders_ssa.c` has two empty functions, as I can't check it without example video file, on which this functions will be called. Please give me test file if you can.
`use_ass_instead_of_ssa` there is, as the format is slightly different, so it is possible to generate a little different files because of different formats .ass and .ssa, but maybe we need only one format.
Please give your opinion about the `ssa_header`, maybe there is something to change in style.
Last pull request was closed because of bug.
> Added basic ASS/SSA encoding support

- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.c
[https://codein.withgoogle.com/dashboard/task-instances/5591734023094272/](url)
I checked the correctness (I had segfault too).
Falling test - the only test that has an argument `-out=null`. But I checked some other files, and they too gave segfault with `-out=null`.
How is it? Firstly, after this line [#1](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/general_loop.c#L930) `enc_ctx` becomes NULL (from function [#2](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/lib_ccx.c#L332)), and we get an error in this line [#3](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/general_loop.c#L933)
If we run it with other files, then we almost always get an segfault error in other places associated with the fact that `enc_ctx = NULL`.
I have …
> Fixed bug with -out=null

- src/ccextractor.c
- src/gpacmp4/mp4.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/spupng_encoder.c
[https://codein.withgoogle.com/dashboard/task-instances/5086033567809536/](url)
Firstly you must make project after changes in code. Go to project folder and run `cmake src` and then `make`.
Run `valgring --leak-check=yes ./ccextractor [args]`.
If we run without arguments, then OK - no leaks are possible
```
==3145== 
==3145== HEAP SUMMARY:
==3145==     in use at exit: 0 bytes in 0 blocks
==3145==   total heap usage: 2 allocs, 2 frees, 1,576 bytes allocated
==3145== 
==3145== All heap blocks were freed -- no leaks are possible
==3145== 
==3145== For counts of detected and suppressed errors, rerun with: -v
==3145== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
Run with random file `valgring --leak-check=yes ./ccextractor /home/izaron/video/itunes.m4v`. Oops, the lake …
> Fixed memory leaks

- src/lib_ccx/ts_info.c
Fixed memory leak
Valgrind log:
```
==24485== 
==24485== HEAP SUMMARY:
==24485==     in use at exit: 31,603,588 bytes in 1,084 blocks
==24485==   total heap usage: 185,004 allocs, 183,920 frees, 3,539,953,180 bytes allocated
==24485== 
==24485== 184,823 bytes in 3 blocks are possibly lost in loss record 1 of 2
==24485==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24485==    by 0x459590: copy_payload_to_capbuf (ts_functions.c:532)
==24485==    by 0x45A17E: ts_readstream (ts_functions.c:774)
==24485==    by 0x45A226: ts_getmoredata (ts_functions.c:801)
==24485==    by 0x449D50: general_loop (general_loop.c:825)
==24485==    by 0x4300B4: main (ccextractor.c:210)
==24485== 
==24485== 31,418,765 bytes in 1,081 blocks are definitely lost in loss record 2 …
```
> Fixed memory leak with XDS videos

- src/lib_ccx/avc_functions.c
Fixed FPS switching
[Issue #431 ](https://github.com/CCExtractor/ccextractor/issues/431)
I tested it also on another video, which also had this bug. See this value write [https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/es_functions.c#L435](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/es_functions.c#L435) I did the same and it works
> Fixed FPS switching

- src/lib_ccx/ccx_encoders_common.c
Issue #430 
This is not a bug - this function is **only** realised for Teletext files
I radically enabled it for all subtitles
Checked on the .bin file, works well
> Fixed -unixts option

- mac/build.command
Issue fixed : https://github.com/CCExtractor/ccextractor/issues/536
> Mac Build : Added missing directory for protobuf-c.

- linux/pre-build.sh
- mac/pre-build.sh
The filename pointed to, was ```compile.h``` which doesn't exist. Actual storing occurs in ```compile_info_real.h``` as correctly written in windows ```pre-build.bat``` ```echo stored all in compile_info_real.h```.
> Corrected filename.

- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_curl.c
To compile with WITH_LIBCURL add in linux/build "-DWITH_LIBCURL" in BLD_FLAGS and "-l curl" in BLD_LINKER.
After code research, I added support for configurable cURL post URL. Already implemented options is "-out=curl" and "-curlposturl [URL]".
It was quite simple, because I used a global variable `ccx_options`.
But there are problem areas. My suggestions:
1. How much reasonable this line in code architecture? [Line](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/params.c#L2246). The same variable belongs to two objects, one of which belongs to another.
2. It may be worthwhile to make the default curl post url? Instead of [line](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/params.c#L2212). Maybe we need to look at the most frequent URL in …
> Added configurable curl post url

- src/gpacmp4/mp4.c
After updating GPAC library my code (from PR #478 from mp4.c) for fixing memory leaks was erased, but memory leaks still exist. I added it again. I think we should inform the GPAC guys about leaks in their code.
> Reopen: fixed memory leaks

- src/lib_ccx/params.c
[Issue](https://github.com/CCExtractor/ccextractor/issues/349)
Using: "ccextractor -stdin [args] < file" or "type file | ccextractor -stdin [args]"
In Linux all was ok because on this platform 'stdin', 'stdout' and 'stderr' are binary by default.
What the difference between O_TEXT and O_BINARY in Windows: in Windows, the 'stdin' default (O_TEXT) behaviour is to treat byte 0x1a as an end of input and close the input, 0x0a (LF) as a new line and convert it to the two bytes 0x0d, 0x0a (CR+LF). There may be other transformations.
Also I have new [issue](https://github.com/CCExtractor/ccextractor/issues/555).
> Fixed -stdin option in Windows

- src/lib_ccx/networking.c
Last PR #547 
[Issue](https://github.com/CCExtractor/ccextractor/issues/378)
I read something in the Internet about multicasting, unicasting, sockets in C, sample programs.
It's strange, but it seems that in the code simply mixed up the lines.
Tons of materials say that we should use `INADDR_ANY` in multicasts, and `addr` in unicasts, but the code is upside down, so if we give multicast address, it will works as unicast, and vice versa.
I fixed it and checked in Windows - works good, this part does not depend on the platform.
> Fixed bug with -udp address

- .gitignore
- windows/ccextractor.sln
- windows/ccextractor.vcxproj
- windows/ccextractor.vcxproj.filters
I did not rename (Debug|Release) to (Debug|Release)-Simple since it looks ugly/redundant in my opinion. I think we should save it.
Added ffmpeg dll-s copy in the folders after build (I missed it in last PR).
Fixed a mess in the filters.
Before PR all configuration already target the platform 120_xp.
"Official" .zip file with all the required dependencies (all .dll files from windows/libs/lib) - https://www.dropbox.com/s/h6oij6r3dzmyqki/ccextractor-dll.zip?dl=0
> Windows update

- src/lib_ccx/hardsubx_utility.c
I have made memory optimization in function edit_distance. This function is calls often in hardsubx, and works for `O(len^2)` time and `O(len^2)` memory. But in fact we can work with **two** massives with size len instead of **len**. With my commit it works now with massive with size of 2*min(len1,len2).
For example, in this two videos: https://abhinavshukla95.wordpress.com/2016/08/18/google-summer-of-code-work-product-submission/ We have maximum wasting of memory in first video 59x59 ints ans in second video 87x98 with example arguments. With my commit we can use memory of 2x59 ints and 2x87 ints respectively.
> Memory optimization in HARDSUBX edit_distance

- src/ccextractor.c
"Info" spam messages from leptonica surprisingly is Windows problem only (I saw it a few issues, but before I thought that in Linux as well). In Linux this is not, so we must not redefine msg severity. Moreover, in Linux for some reason "L_SEVERITY_NONE" is not defined (maybe it was necessary to compile leptonica from the current master? While on windows used 1.74), so I think it's better to leave it on Windows
> Fixed lept msg severity in linux

- src/lib_ccx/ccx_encoders_ssa.c
When I created the decoder, I could not check function write_cc_bitmap_as_ssa with ENABLE_OCR, and then I fixed one bug - we should change newline symbols in SSA to "\\N"
> Fix SubStation Alpha subtitles in bitmap

- src/lib_ccx/activity.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/dvb_subtitle_decoder.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/params.c
> Fixed DVB subtitle timing and added -debugdvbsub parameter for DVB sub debug traces

- src/lib_ccx/ccx_encoders_smptett.c
**Before :**
```
<p ...>
<span>Hello <font color="#ff0000">red on yellow</font>!
<style tts:backgroundColor="#000000FF" tts:fontSize="18px"/></span>
</p>
```
**Now :**
```
<p ...>
<span>Hello <span>red on yellow<style tts:backgroundColor="#FFFF00FF" tts:color="ff0000" tts:fontSize="18px"/></span>!
<style tts:backgroundColor="#000000FF" tts:fontSize="18px"/></span>
</p>
```
Also, fix for the annoying appearance of garbled text at the end of sentence.
I tried my best to explain the implementation using comments. In case of any doubt/ issue, please give feedback. :)
> SMPTE-TT : Added support for font color.

- src/lib_ccx/ccx_encoders_sami.c
Fixed the extraction of DVB subtitles to SAMI format. There was a problem when a subtitle had multiple lines but program interpreted them as different subtitles with same timing.
(Last commit fixed a problem where program skipped subtitles when extracting DVB to SAMI and TTML.)
> Fixed DVB to SAMI extraction.

- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/params.c
Work in progress - translating CEA-608 subs to WebVTT
**Done:**
- Support of the raw old format without colors
- Added colors and fonts with segments (consecutive characters of the same font or color)
**Todo:**
- Replace current "webvtt" to "webvtt-raw" and "webvtt-full" to "webvtt" (???)
- Add XDS [metadata](https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#metadata-xds) what **already** computed by CCExtractor and written on screen; and add it in file
- True positioning as in document
- Anything else missing from the [document](https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html)
@cfsmp3 Write your suggestions
> C608 to WebVTT translation

- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/params.c
Last PR: https://github.com/CCExtractor/ccextractor/pull/599
What is done
- Fixed minor bugs
- Added "webvtt-full" and "--webvtt-create-css" parameter
- Added CSS settings inline and outline for styling
- Added recognition of the segments in text where it is necessary to add `<c.color>`, `<i>` or `<u>` and closing tags
- Added positioning of the caption lines. One line now is one cue as says in docs 
> It is recommended to create a separate WebVTT cue when a different PAC is used for lines of captions that are on screen at the same time
> C608 to WebVTT translation - Part 2

- src/lib_ccx/wtv_functions.c
This quick fix should correct the change introduced in dd8923b2e4b4af08b3322811af4f8d7aad953e0e that broke (some?) WTV timings. Reported in #452.
> Fix for bad WTV timings (#452)

- src/ccextractor.c
- src/gpacmp4/mp4.c
- src/lib_ccx/ccx_common_common.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/myth.c
Previous PR: https://github.com/CCExtractor/ccextractor/pull/535
> return a non-zero return code if no subtitles were found

- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_demuxer.h
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/telxcc.c
- src/lib_ccx/ts_functions.c
- src/lib_ccx/ts_tables.c
- Implemented -pesheader dump parameter for teletext packets too
- Fixed Teletext timing
- Implemented method for getting global minimum PTS of all 51 possible stream ids and minimum PTS for subtitles, video and audio only.
- Almost fixed DVB timing (now it's in sync with video only)
- Fixed Teletext subtitle duplication (Closes #492)
- Fixed Teletext zero length subtitles (Closes #562)
> Fixed Teletext related issues (+DVB) and added other stuff

- src/lib_ccx/ccx_decoders_708.c
- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_decoders_708_output.h
#Getting started on improving
Closes #477 - result file [DancingQueen.p2.svc01.srt ](https://gist.github.com/Izaron/44c030eae8c6c1049ae6d3e6c6d0dd32)
There are 2 other issues in the list with Korean subtitles, but I do not know whether it is possible to close them
Now correctly displayed characters like ® 
There still characters missing in some lines in English subtitles
> Fixes in CEA-708

- docs/README.TXT
- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_demuxer.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/ts_functions.c
- src/lib_ccx/ts_functions.h
- src/lib_ccx/ts_tables.c
- Implemented method for getting the minimum PTS of video within the first GOP
- DVB is currently in sync with audio (teletext is global, might have to be in sync with audio only too)
- Added function to extract PTS from a PES header
> Perfected DVB timing and cleaned up code.

- src/ccextractor.c
- src/lib_ccx/params.c
Since GPAC needs a file to be present, MP4 files used to crash on stdin. This PR restricts usage of stdin with MP4 files.
Closes #555 .
> Prevent usage of stdin with MP4 files.

- src/lib_ccx/ccx_decoders_708_output.c
Fixed bug with uncorrect srt numbers - [histw-false.srt](http://paste.ubuntu.com/23793294/), [histw-true.srt](http://paste.ubuntu.com/23793345/)
We had a "disappearing subtitles", but in fact we had uncorrect numbering in tv->cc_count and decoder->tv->cc_count, because we increase these values before output function calling, but the output sometimes failed, because the window does not exist, so we can't use this value as counter. I used encoder->cea_708_counter as global correct counter for CEA-708.
> CEA-708 subtitle counter

- src/lib_ccx/ccx_decoders_708.c
- Updated window info dump
- Realised missing BS command
In one of the examples with BS command - before:
```
66
00:04:08,965 --> 00:04:09,599
<font color="aaaaaa">Perhaps there''s anothr</font>
<font color="aaaaaa">place where David Wong</font>
200
00:09:06,230 --> 00:09:07,396
<font color="aaaaaa">Maybe Wong''s suicide noe</font>
<font color="aaaaaa">was legit after all.</font>
```
After:
```
66
00:04:08,965 --> 00:04:09,599
<font color="aaaaaa">Perhaps there's another</font>
<font color="aaaaaa">place where David Wong</font>
200
00:09:06,230 --> 00:09:07,396
<font color="aaaaaa">Maybe Wong's suicide note</font>
<font color="aaaaaa">was legit after all.</font>
```
> 708 fixes 

- .gitignore
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_splitbysentence.c
- src/lib_ccx/utility.c
- src/lib_ccx/utility.h
- tests/Makefile
- tests/README.md
- tests/ccx_encoders_splitbysentence_suite.c
- tests/runtest.c
- tests/samples/sbs_append_string_00
- tests/samples/sbs_append_string_01
In this PR:
* use Levenshtein distance for joining subs into sentences (allow to fix errors)
* SBS tests are moved to separated files
* SBS buffer removed from `encoder_context`, SBS uses its own buffers and structures
The code is still dirty, but it already works good enough
**Important notice**
SBS is color-blind, so `<font>` tags cause errors in resulting output (`</font>` will be placed in **next** sub). Please, run `ccextractor -sbs` only with `-nodvbcolor`
> Improve SBS

- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/general_loop.c
> Fix defects

- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/hardsubx.c
- src/lib_ccx/ocr.c
- src/lib_ccx/params.c
> Added OEM mode parameter

- src/ccextractor.c
- src/gpacmp4/mp4.c
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_mp4.h
- src/lib_ccx/params.c
Various files such as MP4 may have *chapter markers* in them. They are also present in the audio books we purchase, for example, from Amazon. , CCExtractor should now be able to extract Chapter Markers too. 🙂 
Usage is simple. To extract chapter markers from a MP4 video file :
```
./ccextractor -chapters file.mp4
```
It will create file.txt with Chapter Markers in OGG format.
Example :
```
Opening file: chapters.mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: moov
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
opening 'chapters.mp4': ok
Writing chapters into chapters.txt
Done, processing time = 0 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
saurabhshri@gsocdev3:~/gpac/bin/gcc/ccextractor/linux$ ls
build …
```
> Ability to extract Chapters from MP4 files.

- windows/ccextractor.vcxproj
Removed DLL requiring in non-full version (full version already works).
Thanks to @saurabhshri for reporting.
It was obvivous but I tested only full version in all dependency hell since I was sure from point what non-full version was not broken.
Can we just replace one .exe file and reupload 0.85 silently?
> Fixed DLL requiring in non-full version

- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_demuxer.h
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/dvb_subtitle_decoder.h
- src/lib_ccx/ts_info.c
- src/lib_ccx/ts_tables.c
- Fixed memory usage and slow speed caused by too many OCR initializations.
(Now there's only one OCR init per program)
> Fixed huge memory usage caused by OCR inits.

- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_webvtt.c
Fixes #683 in a more consistent manner (no mixing of CRLF and LF), and obeys the -lf parameter.
> Webvtt new fix

- .gitignore
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/telxcc.c
Earlier even when captions were extracted, the return code was 10 and there was prompt no captions found.
Also, teletext page should now appear correctly instead of `cc?`. 
-unixts param works for teletext for .bin
Earlier : 
```
19700101000041.940|19700101000045.000|CC?||The whole forest is disappearing underground!
19700101000045.100|19700101000048.080|CC?||<font color="#00ffff">Disappearing? Are you sure, Mofy?</font>
19700101000048.180|19700101000052.040|CC?||I've just seen it! I couldn't believe my eyes.
19700101000052.140|19700101000054.280|CC?||Mogu, your bag!
```
Now :
```
20170123191246.100|20170123191249.080|801|<font color="#00ffff">Disappearing? Are you sure, Mofy?</font>
20170123191249.180|20170123191253.040|801|I've just seen it! I couldn't believe my eyes. …
```
> Fixes for teletext in .bin files (-unixts param, proper return code, -ucla param).

- src/lib_ccx/matroska.c
__builtin_clz and __lzcnt16 have different output on different machines, so removed this
> Removed builtin code in Matroska

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
---
This pull request adds the next things to the repository:
- A contributors guide
- A template for new issues
- A template for new pull requests
It also updates the readme to reference to the contributors guide, as well as updating all links to the ccextractor homepage with http*s*
> [IMPROVEMENT] Add templates for issues and PR's

- src/lib_ccx/lib_ccx.h
- src/lib_ccx/matroska.c
- src/lib_ccx/utility.c
---
This is quick PR in which :
Removed code with redundant functionality.
- extracting filename without extension
- generating timestamp for srt format from milliseconds
Checked for all samples from #705  .
Also removed a deprecated function which is no longer anywhere used (`timestamp_to_smptetttime`).
> [IMPROVEMENT] Cleaning and replacing redundant code with already existing functions.

- src/lib_ccx/telxcc.c
---
PTS and FTS were not being updated when processing Teletext packets - Fixes #698
> [FIX] Fix PTS and Length in preview section (Teletext subtitles)

- src/lib_ccx/ccx_decoders_isdb.c
---
Some ISDB streams claim to have rollup mode disabled even though they broadcast rollup captions. This PR forces deduplication to happen when -noru is passed irrespective of what the stream says.
> [FIX] Forcing -noru to cause deduplication in ISDB

- src/lib_ccx/ocr.c
---
Sometimes when DVB subtitle bitmaps involved transparent backgrounds, Tesseract OCR would fail to accurately recognize the text, which led to nonsensical outputs. This can be fixed by first converting the Leptonica pix used by Tesseract to a grayscale which solves the problems caused by the transparent elements.
This is a well documented problem on the Tesseract repository.
> [IMPROVEMENT] Adding grayscale conversion for better OCR

- README.md
- src/CMakeLists.txt
---
- Fix CMakeLists for MacOS and Linux. With #742 and this, CCExtractor could be build across all three platforms using CMake.
- Cleanly format the compiling documentation and cmake instructions.
> [Fix] [IMPROVEMENT] Fix CMake across all platform and clean compiling documentation.

- linux/Makefile.am
---
Recently `ccextractor.h` was added in source but `Makefile.am` wasn't updated for the same due to which build with autoconf script was failing. This PR fixes the issue.
> **[FIX]** Fix failing build with autoconf due to ccextractor.h

- linux/builddebug
---
After recent commits, `builddebug` was not updated leading to broken build script.
> [FIX] Include Python API changes in builddebug to fix it.

- src/lib_ccx/ccx_encoders_common.c
---
When the `-out=raw` option is used, the ccextractor jumped to spupng output
format, generating broken files in spupng format without CC data.
With this fix, now it generates CC data in McPoodle's Broadcast format.
> [FIX] Output CC data when -out=raw is used

- src/lib_ccx/ccx_encoders_srt.c
> [FIX] Use proper newlines while printing SRT from bitmaps.

- linux/Makefile.am
---
I was trying to use the `package_creators/rpm.sh` script, but kept running into this error:
```
make  dist-gzip am__post_remove_distdir='@:'
make[2]: *** No rule to make target `src/extractors/wrapper.h', needed by `distdir'.  Stop.
make[2]: Entering directory `/mnt/build/ccextractor'
make[2]: Leaving directory `/mnt/build/ccextractor'
make[1]: *** [dist] Error 2
make[1]: Leaving directory `/mnt/build/ccextractor'
mv: cannot stat '*.gz': No such file or directory
mv: cannot stat '*.tar.gz': No such file or directory
error: File /mnt/build/ccextractor/package_creators/RPMBUILD/SOURCES/ccextractor-0.85.tar.gz: No such file or directory
Sorry, the …
```
> [FIX] Fix path to wrapper.h in Makefile.am

- package_creators/ccextractor.spec
---
Change the location that the binary gets installed from `/usr/local/bin` to `/usr/bin`
> [IMPROVEMENT]: change rpm installation location from /usr/local/bin to /usr/bin

- package_creators/rpm.sh
---
The `rpm.sh` script should preserve the source RPM in addition to the binary RPM as some organizations are required to keep them for things like GPL compliance.
> [IMPROVEMENT] Modify rpm.sh package script to preserve the source rpm

- mac/Makefile.am
---
Fixes CCExtractor building on macOS through Autotools.
> [FIX]Update mac/Makefile.am for working Autotools build on mac

- src/gpacmp4/avilib.c
---
This PR fixed these compiler warnings:
../src/gpacmp4/avilib.c:35:0: warning: "PACKAGE" redefined
#define PACKAGE "GPAC/avilib"
<command-line>:0:0: note: this is the location of the previous definition
../src/gpacmp4/avilib.c:36:0: warning: "VERSION" redefined
#define VERSION GPAC_FULL_VERSION
> [FIX][gpacmp4/avilib.c]: Fix redefinition of VERSION and PACKAGE

- src/lib_ccx/ccx_gxf.c
- src/lib_ccx/ccx_gxf.h
- src/lib_ccx/ffmpeg_intgr.c
- src/lib_ccx/ffmpeg_intgr.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/ts_functions.c
---
This PR makes the CCExtractor more standardized, avoid future bugs and allow us to remove the unnecessary *switch (stream_mode)* inside the *while* loop in general_loop().
> [IMPROVEMENT] function header in "get_more_data" functions were standarlized.

- .gitignore
- docs/CHANGES.TXT
- docs/README.TXT
- linux/Makefile.am
- linux/configure.ac
- mac/Makefile.am
- mac/configure.ac
---
Modified Autoconf scripts to enable tarball generation for macOS ( and non *NIX systems including macOS).
Also, modified scripts to include GUI resource files (icons and fonts) in tarball as well.
> [IMPROVEMENT]Modify Autoconf scripts to generate mac compatible tarball

- src/libpng/png.c
- src/libpng/png.h
- src/libpng/pngconf.h
- src/libpng/pngerror.c
- src/libpng/pngget.c
- src/libpng/pnginfo.h
- src/libpng/pngpread.c
- src/libpng/pngpriv.h
- src/libpng/pngread.c
- src/libpng/pngrtran.c
- src/libpng/pngrutil.c
- src/libpng/pngset.c
- src/libpng/pngstruct.h
- src/libpng/pngtrans.c
- src/libpng/pngwrite.c
- src/libpng/pngwutil.c
---
* Current Version of LibPNG is 1.6.27 last updated 11 months ago.
* Latest version for LibPNG is 1.6.34 last modified  2017-09-29.
> [IMPROVEMENT]Update LibPNG from 1.6.27 to 1.6.34

- .travis.yml
Fix one of the builds for Travis
Revert "Upgrade UTF8proc"
This reverts commit 76dc96936315bb92e03849881a7380485931077d.
---
one of the builds actually never started
> [FIX] Fix One of the Travis Builds

- docs/CHANGES.TXT
- tools/histogram.py
---
A histogram in one-minute increments of the number of lines in a subtitle file.
It is tested in Python 3.5.4 and Python 2.7.12.
> [FEATURE] Histogram in one-minute increments of the number of lines in a subtitle file.

- src/lib_ccx/telxcc.c
---
Fixes #829
--sentencecap works for the given teletext sample.
> [FIX] Fixed --sentencecap for teletext samples

- src/lib_ccx/ocr.c
---
Fix crash problem mentioned in #840 .
Possibly I will fix other bugs mentioned in that issue in this pr, or I'll open another PR if you want to merge it first.
> [FIX] Fix crash when image passed into OCR is empty

- docs/CHANGES.TXT
- src/GUI/popups.c
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/networking.c
- src/lib_ccx/networking.h
- src/lib_ccx/params.c
- src/lib_ccx/params_dump.c
---
This is a simple change to allow for binding to source-specific multicast UDP feeds.
I've modified the GUI to allow for enough characters to bind to a SSM address, but it doesn't seem to work, even for simple UDP feeds. Can anyone confirm that the GUI works with UDP?
Also, I tried to validate that it works with Windows, but was unable. I see the packets in wireshark, but all of `ccextractor`, `vlc`, and `mpv` do not seem to get anything. If someone with more Windows-fu can validate that would be great.
> [FEATURE] Support for Source-Specific Multicast

- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/ocr.c
---
Fix #840 
- Fix the bug that only the first line of text from each caption is shown.
- Fix the bug that the last caption is missing.
- The shifting time isn't really a problem because it is indeed shifting a little bit in the video and the conversion from fps->1000 will also cause some precision problems.
> [Fix] Fix DVB bug (Multiple-line subtitle; Missing last line)

- src/lib_ccx/dvb_subtitle_decoder.c
Removed debug code. No idea why it causes travis fails to build
---
Put debug code into ifdef to avoid failing compilation when OCR is disabled.
> [Fix] Put OCR specific code inside ifdef

- src/lib_ccx/ocr.c
---
Tesseract caused some previous problems with lots of newlines, which would cause issues with output being full of empty and useless whitespace. PR checks each line of text for any content, and moves up to the next line if there is no content.
> [IMPROVEMENT] Checks for text before newlines on DVB subtitles

- src/lib_ccx/ocr.c
---
Fix a heap corruption in add_ocrtext2str
> [FIX] Fix a heap corruption in add_ocrtext2str

- src/lib_ccx/ccx_encoders_spupng.c
---
Fix a bug that caused -out=spupng sometimes crashes
> [FIX] Fix a bug that caused -out=spupng sometimes crashes

- .travis.yml
---
During installing the dependencies, one of the command forgets to exit the directory:
```
if [[ $TRAVIS_OS_NAME == 'linux' ]]; then wget https://github.com/DanBloomberg/leptonica/releases/download/1.74.4/leptonica-1.74.4.tar.gz && tar xvf leptonica-1.74.4.tar.gz; cd leptonica-1.74.4; ./configure && make && sudo make install; fi
```
It makes `cd linux; ./build; cd ..; fi` fail to execute.
I also changed `install` to `before_install`, as suggested by travis:
> In a before_install step, you can install additional dependencies required by your …
> [FIX] Fix Travis CI not executing `linux/build`

- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ffmpeg_intgr.c
- src/lib_ccx/ffmpeg_intgr.h
- src/lib_ccx/general_loop.c
> [IMPROVEMENT] Fix some warnings (#896 )

- src/gpacmp4/mp4.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
---
This will fix #807 .
**FEATURE:**
- sbtl:tx3g and text:tx3g handler.
- Support multitrack subtitles.
**KNOWN ISSUES:**
- Styles & extensions of tx3g subtitles are ignored.
- The empty default file will be created, even though sometimes(when there're multiple tracks) we don't use it.
- `-o outputfilename` option is not honered. I don't think I caused it though. It seems to be broken long time ago.
**NOTE:**
- I didn't test the situation when a sample has multiple atoms in it (Is it possible? I don't have a video sample to verify).
- Although I …
> [FEATURE] Support mp4 tx3g & multitrack subtitles

- src/lib_ccx/params.c
---
Add default fonts in the --help.
> [IMPROVEMENT] Minor changes - Add default fonts in the --help

- README.md
---
GitHub may cache a badge, that prevents it from updating automatically. maxAge is a cache-control header that defines after what time the response should be fetched again. It is set to 30 minutes currently.
> [FIX] Prevent GitHub from caching the README badge

- src/lib_ccx/telxcc.c
---
Currently setting a colour doesn't necessarily add a space even though the specifications mandate it. This commit is designed to change that.
This is designed to fix a different problem than #922. There is currently no space when the colour changes in teletext (except with --nofontcolor). See for example [this sample](https://github.com/CCExtractor/ccextractor/files/1721771/Sample.zip) which contains multiple instances of what I am talking about. The default output (with colours) contains the following (only lines that show this have been kept):
```
2
00:00:03,240 --> 00:00:06,039
<font color="#ffff00">Dann räumen wir</font>
<font color="#ffff00">mal aus, oder?</font><font color="#00ffff">Ja.</font>
4
00:00:18,200 --> …
```
> [FIX] Minor issue with spaces in teletext

- src/lib_ccx/telxcc.c
---
Attempt to solve issue #922 by replacing 0xB and 0xA in the middle of row with space character
Generated srt:
Playing the generated srt on windows 10 Movies & TV app:
> [FIX] DVB Teletext subtitle incomplete #922

- src/lib_ccx/ocr.c
- src/lib_ccx/params.c
---
This pull request aims at simplifying and making the -quant 0 parameter faster. It does so by reducing the number of distinct color shades available in the palette of the PNG image under processing. 
An example would be, say a palette color is (248, 187, 027). The new algorithm reduces this image to (224, 160, 0). This is one quantised value amongst the (8*8*8) which can be formed under this algorithm. Since the color palette is reduced and our rect bitmap structures point to palette for their pixel color value; in a way this algorithm …
> [IMPROVEMENT] Modify -quant 0 option

- src/lib_ccx/params.c
---
Bug introduced in #939 
Removed utf8proc which make couldn't identify.
> [FIX]Fix failing cmake due to liblept/tesseract header files

- src/lib_ccx/params.c
---
The problem in accessing uft8proc functions was because the src file was not included in cmake.
utf8proc version is now displayed fine.
> [FIX] Add utf8proc src file to cmake, updated header file

- docs/HARDSUBX.txt
---
To build ccextractor with hardsubx support on linux, we need to configure
ccextractor with the `-enable-hardsubx` switch along with the
`ENABLE_HARDSUBX` flag passed during compilation with make. This commit
adds the missing configure instruction.
> [IMPROVEMENT] Add instruction required to build ccextractor with hardsubx support

- src/gpacmp4/isom_write.c
- [ x] I have checked that another pull request for this purpose does not exist.
- [x ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ x] I have used CCExtractor just a couple of times. …
> [FIX] Implicit declaration of these functions throws warning during build

- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_encoders_common.c
---
This commit adds some checks to avoid segmentation faults.
* In `add_cc_sub_text()`, strdup will cause a segfault if we duplicate an
empty string.
* In `init_encoder()`, initialize pointer fields to NULL to avoid random
addressing so we can avoid illegal memory accessing and segfaults in
other places.
> [FIX] Fix segfault in add_cc_sub_text and initialize to NULL in init_encoder 

- src/lib_ccx/params_dump.c
---
Solves #953 
Concerns #929 
Displays the quantization mode used as shown in the below screen-shot. 
Argument set in above subtitle extraction is "-quant 2"
> [FEATURE] Display quantisation mode

- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_splitbysentence.c
- src/lib_ccx/ocr.c
- src/lib_ccx/params.c
---
Fix #955 
The addition of check for "tlt_config.nofontcolor" allows CCExtractor to skip detecting colors in the Optical Character Reading mode.
arguments used for nofc:  
`-nofc -in=ts -nobom -trim -noteletext -codec dvbsub -dvblang bul -ocrlang bul animalplanet.ts`
arguments used without nofc:
`-in=ts -nobom -trim -noteletext -codec dvbsub -dvblang bul -ocrlang bul animalplanet.ts`
> [FIX]-nocf not working with OCR'ing

- src/lib_ccx/hardsubx_decoder.c
---
The start and end timestamps of extracted burned in captions are flawed
and off by a large difference. Also, the start time of the first burned
in caption extracted is always zero, which is not always the case. And
the extracted captions always appear in continuous timestamps.
To see that, you can download this file from the UK TV Samples in the samples repository:
https://drive.google.com/open?id=0B_61ywKPmI0TdlRWcVdnajVJUWs
Since the duration of that file is 15 minutes, we can trim it down to 30 seconds for our purposes:
`ffmpeg -i BBC1.mp4 -acodec copy -vcodec copy -scodec copy -ss 00:00:00 -t 00:00:30 bbc.mp4`
This will generate the first …
> [IMPROVEMENT] [FIX] Improve the start and end timestamps of extracted burned in captions

- src/CMakeLists.txt
---
Fixes #964 
To allow building with hardsubx, option has been added along with checking for the libraries it requires which have been cross-checked with Makefile.am
https://github.com/CCExtractor/ccextractor/blob/3d6a9f4d57e5fb63b004f5b341a310e8d931f7cf/linux/Makefile.am#L330
Below is the build result after implementing the changes and using cmake.
`make -j8` was successful in compiling the source code. Below is the command used on a file to test.
The required library for building with FFMPEG, "avfilter", was not listed in the required libraries …
> [FEATURE] Allow build with hardsubx using cmake

- src/lib_ccx/hardsubx_classifier.c
---
`strdup` will give a segmentation fault if the argument passed to it is
`NULL`. `TessResultIteratorGetUTF8Text` returns a `char*` which can be `NULL`
and we should not call `strdup` directly over it. Once we check if the
value returned is not `NULL`, then we can call `strdup`.
This also fixes #928.
> [FIX] Fix possible segfaults in hardsubx_classifier.c due to strdup

- src/lib_ccx/CMakeLists.txt
---
Currently, during the building process with the "-HARDSUBX" parameter (implemented in #966 ) and cmake, the below error pops up.
This error is caused since there is no setting for HARDSUBX in the CMAKELISTS.txt present inside the src/lib_ccx directory and hence the "-ENABLE_HARDSUBX" remains off.
This pull request fixes the error by adding the parameter and it's settings to the Cmake file.
[Tested independently on Digital Ocean server]
> [FIX] Correct -HARDSUBX Bug In CMake

- linux/pre-build.sh
- mac/pre-build.sh
Whilst working on the Reproducible Builds effort [0], we noticed
that ccextractor could not be built reproducibly.
This is due to it including the current date.
This was originally filed in Debian as #896867 [1] and uses the
SOURCE_DATE_EPOCH environment variable [2].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/896867
[2] https://reproducible-builds.org/specs/source-date-epoch/
> Make the build reproducible

- docs/HARDSUBX.txt
- docs/using_cmake_build.txt
- src/lib_ccx/params.c
---
There are no parameters as o1 or o2 in ccextractor but they have been mentioned in the help.
This commit removes such instances from file(s).
The parameters were [dropped](https://github.com/CCExtractor/ccextractor/issues/374#issuecomment-222220372), and now to use -1, -2 ...
*Change severity: trivial*
fixes #973
> [IMPROVEMENTS] Update CLI help and HARDBUX Installation Instructions

- docs/using_cmake_build.txt
- [x ] I have checked that another pull request for this purpose does not exist.
- [x ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x ] I am an active contributor to CCExtractor.
--- …
> [FIX] Correct typographical error

- src/lib_ccx/ccx_decoders_708.c
- [ x] I give this submission freely, and claim no ownership to its content.
- [ x] I am an active contributor to CCExtractor.
---
Whenever ClearWindow command is issued to currently visible window , the captions stored in window are not copied to screen , since only toggle, hide window and delete window command do that right now , therefore data was out, with this PR , the caption are copied to screen and printed if there is some data and window was visible when Clearwindow was issued.
> Fix caption loss due to CW command

- src/CMakeLists.txt
---
Linux Distribution Details:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
Failing cmake command:
cmake -DWITH_FFMPEG=ON ../src/
Passing cmake command:
cmake ../src/
Error Seen while compilation:
Linking C executable ccextractor
/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [ccextractor] Error 1
make[1]: *** [CMakeFiles/ccextractor.dir/all] Error 2
make: *** [all] Error 2
> [Fix] Compilation using cmake on linux

- docs/CHANGES.TXT
- src/lib_ccx/ocr.c
---
Remove multiple RGB to grey conversion while OCR
> [IMPROVEMENT]Remove multiple RGB to grey conversion while OCR

- docs/CHANGES.TXT
- src/ccextractor.c
---
I found out that ccextractor didn't display non-Latin characters in stdout. There were problems displaying input files with russian letters, subtitles which contain non-Latin symbols (with -stdout parameter) and so on. Fixed this problem.
* Strange symbols in Input filename before changes
* Fixed non-Latin letters
> [FEATURE] Added support for non-Latin characters in stdout

- src/ccextractor.c
- src/lib_ccx/file_functions.c
- src/lib_ccx/params.c
- src/lib_ccx/params_dump.c
---
If CCExtractor is passed an empty argument, it tries to open it as a file. E.g.
`ccextractor ""` OR
`ccextractor {file1} "" {file2}`
In case of multiple input files, if one or more failed to open, CCExtractor exists with the message `Failed to open input file: File does not exist.` Since my second parameter was an empty filename `""` (came from an empty key in a script), I kept on thinking somehow "," is being appended to filename. 
It showed : `Input: filename,`.
With this PR:
- If filename is empty, that file is skipped.
- If one or more file fails to open, it tells that.
- Shows number of files while dumping parameters.
> [IMPROVEMENT] Don't add files with empty filename & show better msg for multiple input files.

- docs/CHANGES.TXT
- src/lib_ccx/ocr.c
When OCR_DEBUG is defined, code will dump more images
to find root cause of failed OCR
---
Add more tapping points while debugging tesseract
> Add more tapping points while debugging tesseract

- src/lib_ccx/file_functions.c
- src/lib_ccx/networking.c
- src/lib_ccx/networking.h
---
So I read that in windows we need to bind to INADDR_ANY only while joining the multicast group, so I left it at that only. Now while receiving the stream from udp multicast, I peak at the header file and match the source ip with the provided ip and only continue if the IPs match. I have tested it on windows using ffmpeg stream system. Let me know if any more changes need to be done.
> [FIX] for issue #668 (Windows and Multicast)

- docs/COMPILATION.MD
---
This is an improvement to the documentation / compile guide: At least in Ubuntu 18.04 (possibly the related Debian version and newer Ubuntus) the package `tesseract-ocr-dev` does not exist anymore. It was replaced by `libtesseract-dev`.
> **[IMPROVEMENT]** Update COMPILATION.MD for Ubuntu 18.04 (and possibly others)

- src/lib_ccx/ts_info.c
---
Fixes #1077. This one-line change ensures that we select only **CCX_CODEC_ATSC_CC** streams with payload.
> **[FIX]** Solve #1077. Add check for empty streams.

- src/lib_ccx/matroska.c
- src/lib_ccx/matroska.h
---
Added support for extracting EIA-608 subtitles from MKV files. For now it works with MP4/h264. Solves #1068, #1070
> [FEATURE] Added support for EIA-608 inside MKV

- .travis.yml
- README.md
- ~[ ] I have mentioned this change in the [changelog]~
---
- Fixed failing Travis build for macOS. Also added cmake build test in the same.
- Removed linux build tests because Sample Platform already covers it.
> [FIX] Travis build for macOS. Also add cmake build test.

- src/lib_ccx/hardsubx.c
- src/lib_ccx/ocr.c
- src/lib_ccx/ocr.h
---
Changed the way Tesseract is initialized in hardsubx to be the same as in ocr.c. Fixed the problem with incorrect pass of pointer to av_frame_free function, which caused segfault.
> [IMPROVEMENT] Change initialization of Tesseract and fix segfault in hardsubx.

- src/lib_ccx/ocr.c
--- 
Fixes segfault when `last_font_tag_end` in **ocr.c** should be empty but is `1` instead.
> **[FIX]** Fixes #1084 by adding check for NULL string in ocr.c

- .github/ISSUE_TEMPLATE.md
---
When https://github.com/CCExtractor/sample-platform/pull/266 was opened i noticed that one part of the Markdown doesn't render because of the space. With this PR I am going to fix that :)
> Fix Video links for not converting to Markdown

- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_webvtt.c
---
addresses #1076 
leaves behind the null terminator bug, but it hasn't been an issue with anything except gedit as of yet.
> [FIX] Remove webvtt styling when not using webvtt-full

- docs/COMPILATION.MD
---
These are CentOS 7 based, but should work across the board, specifically including 8. I've tested in CENTOS 7 and Fedora 30
> [IMPROVEMENT] Add RHEL based distros instructions.

- src/lib_ccx/ffmpeg_intgr.c
---
Simple fix for FFMpeg header
> [FIX] FFMpeg: avfilterhraph.h merged with avfilter.h.

- docs/CHANGES.TXT
- src/lib_ccx/ccx_demuxer_mxf.c
---
Update the MXF demuxer so that it parses frame rates out of the CDP data.  Without this, ccextractor assumed 29.97 fps in all content, so for example, on a 59.94 fps file the caption timings were double what they should be.
> [IMPROVEMENT] MXF caption frame rates

- docs/CHANGES.TXT
- docs/COMPILATION.MD
- linux/Makefile.am
- mac/Makefile.am
- src/gpacmp4/mp4.c
- src/lib_ccx/CMakeLists.txt
- src/lib_ccx/activity.c
- src/lib_ccx/avc_functions.c
- src/lib_ccx/avc_functions.h
- src/lib_ccx/ccx_common_constants.h
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_common.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_mcc.c
- src/lib_ccx/ccx_encoders_mcc.h
- src/lib_ccx/es_functions.c
- src/lib_ccx/es_userdata.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/matroska.c
- src/lib_ccx/myth.c
- src/lib_ccx/params.c
- src/lib_ccx/sequencing.c
- src/lib_ccx/utility.c
- windows/ccextractor.vcxproj
> [FEATURE] Added support for encoding into an MCC File. (CCExtractor#733)

- docs/COMPILATION.MD
---
- Improve the structure of package installation command to make it easy to copy and paste
- Improve the formatting of code blocks by mentioning language as specified by MD
> [IMPROVEMENT] Make COMPILATION.md Easier To Use

- src/lib_ccx/telxcc.c
Check for null pointer before extracting data
- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that another pull request for this purpose does not exist.
- [ X] I have considered, and confirmed that this submission will be valuable to others.
- [ X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ X] I give this submission freely, and claim no ownership to its content.
- [ X] **I have mentioned this change in the …
> [FIX] Fix for crash while fixing sentence case

- README.md
---
For people new to the software it can be a challenge to use it for the first time. By adding this to the README they can see the file formats supported and how the software works without having to search for their own file. This will be especially helpful to the many new GCI students who likely don't have much experience in the TV industry but want to learn how the software works.
> [IMPROVEMENT] Add TV Samples to README

- docs/CHANGES.TXT
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/dvd_subtitle_decoder.c
- src/lib_ccx/ocr.c
---
Issue #1128
Changes:
- checking if pointer isn't NULL in get_bitmap in file dvd_subtitle_decoder.c
- checking in 3 places if the height or width isn't negative value
- setting default value of ctx->is_alloc
- checking if ctx->pos > ctx->len in decode_packet in dvd_subtitle_decoder.c
- changed changes.TXT
> [FIX] Segmentation fault on VOB #1128

- src/utf8proc/utf8proc.h
---
Added back the define so that CCExtractor would build properly on Windows:
```
#define UTF8PROC_STATIC
```
in utf8proc.h
Tested on Windows 10 x64 using Visual Studio 2019.
> [FIX] Added back define to make building on Windows work again

- docs/CHANGES.TXT
- src/ccextractor.c
- src/ccextractor.h
---
The `check_configuration_file` function takes in a dereferenced `ccx_s_options` struct as `api_options`, and calls `parse_configuration` by taking a reference to `api_options` . However, the only call to `check_configuration_file` is made by dereferencing a `ccx_s_options` struct, meaning `parse_configuration` can be called directly. Hence, there is no use for `check_configuration_file`, meaning it can be safely deleted.
> [IMPROVEMENT] Removed redundant check_configuration_file function

- docs/CHANGES.TXT
- src/lib_ccx/networking.c
---
#1116
The change allows the command-line version of ccextractor to be built for Windows XP and run on it as well.  The following occurs without the changes because inet_ntop() is not supported on Windows XP.
CCX was built on a Windows 10 machine using Visual Studio 2017 targeted for Windows XP and then run on a Windows XP VM. Visual Studio 2019 doesn't support targeting for Windows XP.
> [FIX] Change inet_ntop to inet_ntoa for Windows XP compatibility

- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_curl.c
- src/lib_ccx/ccx_encoders_g608.c
- src/lib_ccx/ccx_encoders_python.c
- src/lib_ccx/ccx_encoders_sami.c
- src/lib_ccx/ccx_encoders_smptett.c
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/ccx_encoders_xds.c
Fix #1103 
Move up the pipeline, when the calculation of delay is done.
> [Fix] Make -delay all output formats

- src/gpacmp4/mp4.c
`freep` already nulls the pointer.
Follow up to #1169
> [IMPROVEMENT] Remove useless nulling of pointer

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/params.c
---
In response to issue #1127, this fix adds an option to remove the X-TIMESTAMP-MAP header for WebVTT.
> [FIX] Added the option to disable timestamps for WebVTT

- src/lib_ccx/ccx_encoders_webvtt.c
---
This fixes erronous code added by #1176.
It also fixes a "vulnerability" added by it which would allow someone with access to the input and output file to leak memory content. (such as with the sample platform).
It is almost unexploitable though due to ASLR.
> [FIX] wrong format string

- src/gpacmp4/mp4.c
- src/lib_ccx/avc_functions.c
- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_xds.c
- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_curl.c
- src/lib_ccx/ccx_encoders_sami.c
- src/lib_ccx/ccx_encoders_smptett.c
- src/lib_ccx/ccx_encoders_splitbysentence.c
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/ccx_gxf.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/ocr.c
- src/lib_ccx/output.c
- src/lib_ccx/params_dump.c
- src/lib_ccx/telxcc.c
- src/lib_ccx/ts_functions.c
- src/lib_ccx/ts_info.c
- src/lib_ccx/ts_tables_epg.c
---
Change `freep` into a macro to remove all the warnings it generated.
> [IMPROVEMENT] Remove freep warning

- src/gpacmp4/mp4.c
- src/lib_ccx/avc_functions.c
- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_xds.c
- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_curl.c
- src/lib_ccx/ccx_encoders_sami.c
- src/lib_ccx/ccx_encoders_smptett.c
- src/lib_ccx/ccx_encoders_splitbysentence.c
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/ccx_gxf.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/ocr.c
- src/lib_ccx/output.c
- src/lib_ccx/params_dump.c
- src/lib_ccx/telxcc.c
- src/lib_ccx/ts_functions.c
- src/lib_ccx/ts_info.c
- src/lib_ccx/ts_tables_epg.c
Reverts CCExtractor/ccextractor#1180
Broke too many stuff. I didn't realise at the time.
> Revert "[IMPROVEMENT] Remove freep warning"

- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
---
Unfortunately, pointers to pointers in C don't really work. The only way is to just cast the pointer.
diff of the output:
```patch
58,74d57
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/avc_functions.c: In function ‘dinit_avc’:
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/avc_functions.c:29:8: warning: passing argument 1 of ‘freep’ from incompatible pointer type [-Wincompatible-pointer-types]
<   freep(&lctx->cc_data);
<         ^~~~~~~~~~~~~~
< In file included from /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/lib_ccx.h:9,
<                  from /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/avc_fun …
```
> [IMPROVEMENT] Remove freep warnings

- docs/CHANGES.TXT
- src/lib_ccx/ccx_encoders_spupng.c
---
For large files (>~1 GB), the out=spupng option would stop prematurely because the FT_Face objects used by the spupng_export_string2png() function were never destroyed.
> [FIX] Add FT_Done_Face to destroy face objects after they're used

- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_splitbysentence.c
---
Removes the following warnings:
```patch
0a1
> Scanning dependencies of target ccx
201,206d201
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_encoders_helpers.c:119:66: warning: pointer targets in passing argument 2 of ‘modification’ differ in signedness [-Wpointer-sign]
<   119 |     modification(index - list->words, data->characters[line_num] + (c - line));
<       |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
<       |                                                                  |
<       |                                                                  unsigned char *
< …
```
> [IMPROVEMENT] Remove warnings

- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/ocr.c
- src/lib_ccx/ts_tables.c
Fix #1161
---
Check against the dvb data instead of passing through `languages`.
Stop checking if OCR lang == dvblang (as it prevents from setting a non ISO dvblang).
> [FIX] Allow `-dvblang` that doesn't follow ISO 639-2

- src/lib_ccx/ccx_encoders_helpers.h
> [IMPROVEMENT] Fix implicit declaration of function 'add_word'

- docs/CHANGES.TXT
- linux/Makefile.am
- mac/Makefile.am
- src/CMakeLists.txt
- src/ccextractor.c
- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
- src/lib_ccx/ccx_common_constants.h
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_decoders_608.c
- src/lib_ccx/ccx_decoders_608.h
- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_mcc.c
- src/lib_ccx/ccx_encoders_scc.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/params.c
- src/lib_ccx/utility.c
- src/lib_ccx/utility.h
- windows/ccextractor.vcxproj
- windows/ccextractor.vcxproj.filters
Fix #1120 
---
Colours haven't been implemented yet.
~~The disassembly format hasn't been implemented yet.~~
> [FEATURE] SCC and CCD encoder

- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/utility.c
---
I restricted the scope and used free because the features of freep
aren't needed here.
Restricting the scope makes it clear when freeing the variable should be
done.
> [FIX] Fix free segfault

- src/lib_ccx/ocr.c
- src/lib_ccx/ocr.h
---
Removes warnings:
```patch
0a1
> Scanning dependencies of target ccx
550,558d550
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_encoders_splitbysentence.c:765:35: warning: pointer targets in passing argument 2 of ‘paraof_ocrtext’ differ in signedness [-Wpointer-sign]
<   765 |  str = paraof_ocrtext(sub, context->encoded_crlf, context->encoded_crlf_length);
<       |                            ~~~~~~~^~~~~~~~~~~~~~
<       |                                   |
<       |                                   unsigned char *
< In file included from /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_encoders_splitbysentence.c:18: …
```
> [IMPROVEMENT] Remove warning when calling paraof_ocrtext

- src/lib_ccx/ccx_decoders_608.c
- src/lib_ccx/ccx_decoders_structs.h
---
This adds a constant with the maximum number of screen rows and replaces hard-coded occurrences of it with the new constant, as hard-coding array lengths everywhere is unclear and prone to breakage. The array lengths in the screen struct were also replaced with constants where applicable.
The cleanup directly ties in with the fix in question, which is to initialize the colora nd font arrays properly using a loop rather than `memset`. The commit message goes into more detail regarding this issue.
GCC 9.2.0 issues a warning here:
```
src/lib_ccx/ccx_decoders_608.c: In function ‘clear_eia608_cc_buffer’:
src/lib_ccx/ccx_decoders_608.c:111:3: …
```
> [FIX] EIA-608 screen clearing fix

- docs/CHANGES.TXT
- src/lib_ccx/ocr.c
---
This leak was detected by Valgrind:
```
==1203168== 2,880 bytes in 57 blocks are definitely lost in loss record 3 of 4
==1203168==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==1203168==    by 0x51ADBEE: strdup (in /usr/lib/libc-2.30.so)
==1203168==    by 0x24D1F8: ocr_bitmap (ocr.c:569)
==1203168==    by 0x24E25B: ocr_rect (ocr.c:907)
==1203168==    by 0x284832: write_dvb_sub (dvb_subtitle_decoder.c:1665)
==1203168==    by 0x284B7A: dvbsub_handle_display_segment (dvb_subtitle_decoder.c:1720)
==1203168==    by 0x285024: dvbsub_decode (dvb_subtitle_decoder.c:1828)
==1203168==    by 0x2406AF: process_data (general_loop.c:648)
==1203168== …
```
> [FIX] Fix minor memory leak in OCR code

- src/lib_ccx/ccx_encoders_scc.c
---
This is how every example appears to be structured, and MPV doesn't display anything without this change.
Before: `e5 f2 e5 20`
After: `e5f2 e520`
> [FIX] Write all SCC characters in pairs (fixes playback in MPV)

- src/lib_ccx/ocr.c
---
And move some processing to compile time. It also uses functions that don't check needlessly against '\0'.
> [IMPROVEMENT] Remove useless O(N) operations and memory allocations

- src/lib_ccx/ccx_encoders_scc.c
---
This includes 2 changes:
- Write EDM codes at end times to clear them from the screen as intended by the captioners
- Show captions at the correct times:
- EOC+ENM *shows* the caption. It doesn't clear it — that's EDM's job.
- The caption is *not* shown immediately after loading. EOC (End Of Caption) is required for it to actually show.
Old behavior:
- Start time: Load caption
- End time: Show loaded caption
New behavior:
- Start time: Load and show caption
- End time: Clear displayed caption
These changes fix the issue where captions were always one line off — that is, caption 1 would show when caption 2 was supposed to show.
> [FIX] Fix SCC timing and lingering captions

- src/lib_ccx/ccx_encoders_scc.c
---
The space was being inserted in the wrong position, so the first character of each caption was being cut off. The last character was also cut off in captions with even lengths.
Thanks to @NilsIrl for reporting this issue.
> [FIX] SCC character pair writing

- src/lib_ccx/lib_ccx.h
---
Removes the following warnings:
```patch
52a52,55
> /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/asf_functions.c: In function ‘asf_readval’:
> /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/asf_functions.c:39:9: warning: ‘rval’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>   return rval;
>          ^~~~
1652a1656,1663
> /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/general_loop.c: In function ‘process_data’:
> /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/general_loop.c:741:5: warning: ‘got’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>   if (got > …
```
> [IMPROVEMENT] Add noreturn attribute to fatal

- src/lib_ccx/ccx_encoders_scc.c
---
This makes the control code handling more readable by adding a small info struct that contains all the information about a control code (first byte odd & even, second byte, and assembly). Information is stored in and retrieved from an array, created using an array initializer with the enum values as indices.
This allows us to remove the massive switch-case blocks, leading to much cleaner and more streamlined code.
I have verified that the output is identical using `diff` for both SCC and CCD formats.
**Depends on #1211.**
> [IMPROVEMENT] Clean up SCC control codes

- src/lib_ccx/ocr.c
---
Fix use-after-free after `realloc`.
> [FIX] use-after-free

- docs/CHANGES.TXT
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/ccx_encoders_smptett.c
- src/lib_ccx/ccx_encoders_splitbysentence.c
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/ocr.c
- src/lib_ccx/ocr.h
---
Implement subtitle modification by moving it into ccx_encoders_common.c.
Add support for all `CC_BITMAP` and `CC_608` subtitles. May segfault without #1216.
> [IMPROVEMENT] Implement subtitle modifications for each encoder

- src/lib_ccx/params.c
---
typo
https://github.com/CCExtractor/ccextractor/blob/7b038ab64905750b7da5320b599504b1ca890aab/src/lib_ccx/params.c#L1942
> [FIX] documentation typo

- src/lib_ccx/ocr.c
---
Allows longer subtitles to work. This wasn't needed in the past as the length was computed each time.
> [FIX] longer subtitles

- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
---
It now returns a value like the rest of the printf family. It doesn't
brute force the amount of memory that needs to be allocated.
It also removes a warning.
```patch
0a1
> Scanning dependencies of target ccx
60,63d60
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_common_common.c: In function ‘fdprintf’:
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_common_common.c:27:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
<    27 |    write(fd, p, n);
<       |    ^~~~~~~~~~~~~~~
69c66
<     inlined from ‘add_cc_sub_text’ at …
```
> [IMPROVEMENT] Improve and simplify dprintf implementation

- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_encoders_scc.c
---
This adds support for all colors defined [here](http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CODES.HTML), as well as their italic variants. **Note that I have not tested the output** because MPV doesn't appear to support SCC colors, VLC freezes while trying to open any SCC file, and I haven't been able to find any other players that support SCC. It looks fine with a visual comparison to the examples from #1120, but an actual test would be nice to have before merging.
> [IMPROVEMENT] Add SCC color output support

- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_scc.c
---
All the SCC and CCD examples I can find have CRLF line endings. VLC and libavformat (used by MPV) don't care, so just go with the popular convention and switch to CRLF. There's no reason a user would want to choose their line endings in this scenario.
This also adds 2 trailing new lines as is the convention for SCC/CCD files.
This addresses one of the items in #1191.
> [IMPROVEMENT] Write CRLF line endings in SCC files

- src/lib_ccx/ccx_common_timing.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/ccx_gxf.c
- src/lib_ccx/file_buffer.h
- src/lib_ccx/ocr.c
- src/lib_ccx/ocr.h
- src/lib_ccx/ts_functions.c
- src/lib_ccx/utility.c
---
This fixes all warnings reported by Clang 9.0.1 in the core CCExtractor code, excluding vendored libraries.
These changes combined with #1204 make all of the core code build with zero warnings on the latest stable versions of both GCC and Clang at the time of writing, both with and without OCR enabled.
> [FIX] Clang warning fixes

- .clang-format
- .github/workflows/format.yml
- src/thirdparty/.clang-format
I am an active contributor to CCExtractor.
---
https://github.com/CCExtractor/ccextractor/pull/1219#issuecomment-580125561
requires #1219
> [IMPROVEMENT] Clang format

- docs/CHANGES.TXT
- src/ccextractor.c
- src/ccextractor.h
- src/lib_ccx/ccx_decoders_708.h
---
GCC 10 defaults to `-fno-common`, which results in multiple definitions of a few variables; this is mentioned in the [GCC 10 release notes](https://gcc.gnu.org/gcc-10/changes.html) and the [GCC 10 porting guide](https://gcc.gnu.org/gcc-10/porting_to.html). Closes #1225.
> [FIX] Fix multiple definitions with new -fno-common default in GCC 10

- .github/workflows/build_windows.yml
---
Removes the workaround that was put in place while waiting for actions/virtual-environments#288 to being fixed.
> [FIX] Remove Windows XP workaround

- src/lib_ccx/ccx_decoders_608.c
This was caused by 19241744d71adeda0f29c553b966236e88312c94, moving from
`unsigned char` to `enums` for colors and fonts. The problem with this is
that each colour isn't one byte next to each other so memcpy and memset
didn't work anymore.
The problem:
```patch
6812,6813c6812,6813
< EDITION OF AMERICA'S NEXT TOP
< <i> MODEL</i> ON WEDNESDAYS.<i>          </i>
---
> EDITION OF<i> AMERICA'S NEXT TOP</i>
> <i> MODEL</i> ON WEDNESDAYS.
6817c6817
< EDITION OF AMERICA'S NEXT TOP
---
> EDITION OF<i> AMERICA'S NEXT TOP</i>
6819c6819
< >><i> THE VAMPIRE DIARIES         </i>
---
> >><i> THE VAMPIRE DIARIES</i>
6824,6825c6824,6825
< >><i> THE VA</i>MPIRE DIARIES
< AND<i> THE SECRET CIRCLE          </i>
---
> >><i> THE VAMPIRE DIARIES</i>
> AND<i> THE SECRET CIRCLE</i>
6829,6831c6829,6831
< >><i> THE …
```
> [FIX] Fix tags displaying incorrectly

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
---
This was discussed already.
This fixes the problem where issues have the instructions in them which can decrease readability.
> [IMPROVEMENT] Comment out issue

- .github/workflows/build_linux.yml
- .github/workflows/build_windows.yml
- .github/workflows/format.yml
This is because contributors don't have branches called master it isn't
possible to manually trigger workflows as suggested by
https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/m-p/31517.
> [IMPROVEMENT] Remove the need for the push to be on the master branch

- docs/CHANGES.TXT
- linux/Makefile.am
---
Fix for issue #1241 , changed linux/Makefile.am to run with updated paths of thirdparty libpng .
> [FIX] Fixed paths in MakeFile, fixing the AutoConf compile error

- .github/workflows/format.yml
This is possible thanks to
https://github.com/actions/virtual-environments/pull/447
> [IMPROVEMENT] Optimize format workflow

- windows/ccextractor.vcxproj
When using a straight-forward way of build the project (prebuilding dependencies through vcpkg and then building the solution), some issues might appear. This is because of ccextractor should be built using already prebuilded ffmpeg libraries (they are supplied). And tesseract might be obtained through "vcpkg".
> Update VS project build settings (issue #1254)

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/hardsubx.c
- src/lib_ccx/ocr.c
- src/lib_ccx/params.c
---
FIx the issue https://github.com/CCExtractor/ccextractor/issues/1264
> [FIX] Allow all oem modes with tesseract v4

- .github/workflows/build_windows.yml
- src/lib_ccx/ccx_common_option.c
---
about bom In the ccextractor help :
```
-bom: Append a BOM (Byte Order Mark) to output files.
Note that most text processing tools in linux will not
like BOM.
This is the default in Windows builds.
-nobom: Do not append a BOM (Byte Order Mark) to output
files. Note that this may break files when using
Windows. This is the default in non-Windows builds.
```
Currently, bom is also enabled in non-Windows builds. This PR fixes this issue.
> [FIX] Disable BOM in non-Windows build

- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_encoders_g608.c
- src/lib_ccx/ccx_encoders_mcc.c
- src/lib_ccx/ccx_encoders_sami.c
- src/lib_ccx/ccx_encoders_scc.c
- src/lib_ccx/ccx_encoders_smptett.c
- src/lib_ccx/ccx_encoders_srt.c
- src/lib_ccx/ccx_encoders_ssa.c
- src/lib_ccx/ccx_encoders_transcript.c
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/file_functions.c
- src/lib_ccx/matroska.c
- src/lib_ccx/utility.c
- src/lib_ccx/utility.h
---
Remove -Wunused-result warnings. The main reason to do this is that contributors aren't flooded with warnings which cause them to ignore them.
output diff:
```diff
244,307d243
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_decoders_708_output.c: In function ‘_dtvcc_write_row’:
< /home/nils/Documents/codein2019/ccextractor/src/lib_ccx/ccx_decoders_708_output.c:194:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
<   194 |   write(fd, encoded_buf_start, encoded_buf - encoded_buf_start);
<       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
< …
```
> [FIX] -Wunused-result warnings

- src/lib_ccx/ocr.h
- [x ] I have checked that another pull request for this purpose does not exist.
- [x ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x ] I have used CCExtractor just a couple of times.
---
Fix for #1258 segmentation fault in hardsubx
> [FIX] hardsubx segmentation fault

- src/thirdparty/gpacmp4/gpac/isomedia.h
There is a small typo in src/thirdparty/gpacmp4/gpac/isomedia.h.
Should read `common` rather than `commmon`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, commmon -> common

- docs/COMPILATION.MD
---
As per the discussion on #1299
**Changes**
- added info about `linux/builddebug` to the compilation doc.
> [DOCUMENTATION] mentioned debug info on compilation docs

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_demuxer.c
- src/lib_ccx/ccx_demuxer.h
- src/lib_ccx/params.c
Remove -cf which is just a rather bad attempt to convert a TS or PS to a ES (by just writing non-headers).
I added it maybe in CCExtractor 0.02 to help me with debugging. I don't need anyone else has ever used it and I know better now :-)
> Remove -cf

- docs/CHANGES.TXT
- src/thirdparty/gpacmp4/gpac/internal/isomedia_dev.h
-   [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
-   [x] I have checked that another pull request for this purpose does not exist.
-   [x] I have considered, and confirmed that this submission will be valuable to others.
-   [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
-   [x] I give this submission freely, and claim no ownership to its content.
-   [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
-   [ ] I have …
> [FIX] Fix segfault on Windows

- src/lib_ccx/params.c
**In raising this pull request, I confirm the following:**
**My familiarity with the project is as follows:**
---
Removes the `-nots` flag from the section of `parse_parameters()` in `src/lib_ccx/params.c` as is not a valid format, and conflicts with it's other use [here](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/params.c#L1508)
> [FIX] remove '-nots' flag from file-format parsing

- src/lib_ccx/ccx_decoders_708.c
---
Fixes issue #677 
Instead of resetting the decoder, when current_length doesn't equal the len in header, change current_length to len(ignore the extra data as padding)
> Ignore extra padding data in the current_packet

- src/lib_ccx/ccx_decoders_708.c
- src/lib_ccx/ccx_decoders_708.h
- src/lib_ccx/ccx_dtvcc.c
Process packet as soon as the packet len is equal to the specified len
---
Process current packet as soon as the packet length is equal to the specified length. This leads to the packet being processed in the current FTS, instead of being processed in the next FTS, like before. Fixes #641 
Also ends up fixing #646, as the last packet is now processed instead of waiting for a next packet which never comes
This is causing the issue #677 again. Working on a fix for that
> Fix 708 timing issue

- src/lib_ccx/ccx_decoders_708.c
---
This reverts commit 7f4acae74b9e1a931cdf10b490fd1e3c4ec73d4c.
Revert changes from #1304
> Revert #1304

- .github/workflows/build_linux.yml
---
As discussed @cfsmp3 , I've added bazel build to Github actions for linux. So whenever a new pr comes from now it'll be tested for bazel build and only if all of the builds which now includes bazel pass, only then a test will be ran for a pr via sample-platform (yet to be done in this year's GSoC). 
CC @canihavesomecoffee
> [IMPROVEMENT] Add bazel build to Github Actions.

- src/lib_ccx/ccx_encoders_webvtt.c
---
with respect to issue #1294, I determined that the segmentation fault maybe due to a lack of a check for context->timing being uninitialised in src/lib_ccx/ccx_encoders_webvtt.c. I have added the check.
> [FIX] segmentation fault on encoding McPoodle's raw to WebVTT

- src/lib_ccx/ccx_encoders_smptett.c
---
So I couldn't find any sort of specification requiring empty p tags to be inserted into the ttml file. Thus I have removed the code that was adding these completely.
> [FIX] Removed extra lines of code which added extra p tags

- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/matroska.c
- src/lib_ccx/telxcc.c
Changes output of gui reports to decouple subtitle and time from 
```
###SUBTITLE###>> NARRATOR: The reports
###SUBTITLE#23:34#23:35#>> NARRATOR: The reports
###SUBTITLE###concurred.
###SUBTITLE#23:35#23:37#concurred.
###SUBTITLE###>> BP has not adequately
###SUBTITLE#23:37#23:39#>> BP has not adequately
```
to
```
###TIME#23:34-23:35
###SUBTITLE###>> NARRATOR: The reports
###SUBTITLE###concurred.
###TIME#23:35-23:37
###SUBTITLE###concurred.
###SUBTITLE###>> BP has not adequately
###TIME#23:37-23:39
```
> modify gui output for easier parsing

- docs/CHANGES.TXT
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_structs.h
- src/lib_ccx/output.c
- src/lib_ccx/params_dump.c
---
* The WEBVTT format issue was introduced in #1092 (after v0.88), so I didn't include it in the changelog. See [WebVTT file structure](https://www.w3.org/TR/webvtt1/#file-structure) for newline requirements.
* Added the WEBVTT header to multitrack output files (mp4).
* Generate multitrack filenames based on the output file instead of the input file. This fixes the situation where the -o argument is used and the first track is saved to the specified output location and the other tracks are saved next to the input file. I added `char *original_filename` to `struct ccx_s_write`, to avoid chained suffixes with three or more tracks (e.g. …
> [FIX] Multitrack, WebVTT, and Segfault issues

- src/lib_ccx/ccx_common_timing.c
- src/lib_ccx/ccx_common_timing.h
---
VOB files can contain multiple chapters in a single file. This causes PTS to reset to 0 when a new chapter starts. This leads to FTS also getting reset. But min and max fts aren't reset. So fixed that
Fixes https://github.com/CCExtractor/ccextractor/issues/1277
> Fix min and max fts when PTS resets

- src/lib_ccx/ccx_decoders_608.c
---
Fix timing zero-ing out, when Direct Rollup is selected
Fixes #1327
> Fix timing zero-ing out, when Direct Rollup is selected

- src/lib_ccx/sequencing.c
Avoid overwriting data, by processing it first
---
Flush buffered cc blocks before storing new ones if FTS has changed, to avoid overwriting subtitle data
> Fix for missing subtitles

- docs/CHANGES.TXT
- src/lib_ccx/general_loop.c
- src/lib_ccx/teletext.h
- src/lib_ccx/telxcc.c
Regression test 78 (https://sampleplatform.ccextractor.org/regression/test/78/view)
has been broken since #622 was merged to fix other issues.
It's been traced back to be caused by not setting t0 at the correct time
(setting it using a calculated PTS time rather than taking it from the video frame),
and this commits attempts to fix that.
> [FIX] Attempt to fix long-running regression in TeleText

- docs/CHANGES.TXT
- src/lib_ccx/ccx_decoders_708_output.c
---
Don't take column length from curr_window, as row could from any window
> Fix column length

- src/lib_ccx/ccx_decoders_708.c
- src/lib_ccx/ccx_decoders_708.h
- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_decoders_708_output.h
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_decoders_structs.h
- src/lib_ccx/ccx_dtvcc.c
- src/lib_ccx/ccx_dtvcc.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/mp4.c
---
Add declarations for undeclared functions
Update naming style for all 708 related functions to have a consistent prefix of `dtvcc_`
> Update function declarations and naming style

- .github/workflows/build_linux.yml
- .github/workflows/build_windows.yml
- .github/workflows/format.yml
- .github/workflows/release.yml
- windows/installer.wxs
- [] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
---
Adds a [WiX](https://wixtoolset.org/)-based .msi installer for Windows releases, and incorporate this in the release process.
Upon the creation of a new release, the release workflow will be triggered (using the tag as partial version number) and append an .msi as artifact to the release. It will pull in the latest available release from https://github.com/CCExtractor/ccextractorfluttergui for use as GUI.
It is currently not yet using the Rust build.
> [IMPROVEMENT] Automate release process for installer

- docs/CHANGES.TXT
- docs/COMPILATION.MD
- linux/Makefile.am
- linux/configure.ac
- mac/Makefile.am
- mac/build.command
- mac/configure.ac
- mac/m4/ax_compare_version.m4
- src/CMakeLists.txt
- src/thirdparty/libpng/arm/arm_init.c
- src/thirdparty/libpng/arm/filter_neon.S
- src/thirdparty/libpng/arm/filter_neon_intrinsics.c
- src/thirdparty/libpng/arm/palette_neon_intrinsics.c
**[FIX]** 
- [ x ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ x ] I have checked that another pull request for this purpose does not exist.
- [ x ] I have considered, and confirmed that this submission will be valuable to others.
- [ x ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ x ] I give this submission freely, and claim no ownership to its content.
- [ x ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
- [ x …
> Repair Mac Build processes

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_decoders_608.c
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/mp4.c
- src/lib_ccx/params.c
Extract CEA-708 subs by default, without the need to pass any parameters.
Current status:- 
- 708(-svc) and field 1(-1) are enabled by default
- if no params are provided:- extract whatever is available, if both(708 and 608) are available then extract both
- If only -1/-2/-12 is provided:- extract only 608 subs
- if only -svc is provided:- extract only 708 subs
- if both -1/-2/-12 and -svc are provided:- extract both 608 and 708
> Extract 708 subs by default

- src/rust/src/decoder/service_decoder.rs
> [FIX] Fix crash in Rust decoder on ATSC1.0 TS Files (#1407)

- docs/CHANGES.TXT
- src/ccextractor.c
---
Using `hardsubx` on samples would lead to a segmentation fault.
The seg fault arose because the `init_libraries` method was called after the `hardsubx` call. 
This pull request moves it to the appropriate place.
> [FIX] segmentation fault when using hardsubx

- .github/workflows/build_linux.yml
- .github/workflows/format.yml
- src/rust/src/decoder/mod.rs
> Fix clippy warning and Use rust 1.56.0 for CI 

- docs/CHANGES.TXT
- src/ccextractor.c
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/general_loop.c
- src/lib_ccx/hardsubx.c
- src/lib_ccx/hardsubx.h
- src/lib_ccx/hardsubx_decoder.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/params.c
- [] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
(Not applicable because still WIP)
---
This PR is in context to issue #726 
The current status is that the generated subtitle file has content from closed-caption extraction and burnt-in extraction, however they are not in the correct order. 
The approach I have in mind right now is to use the timestamp of previously encoded subtitles of one of the modes (burnt-in or closed caption) and make a decision on which packet to process (the image or the closed caption) 
Please advise on whether this approach looks okay. 
Note: …
> add option to extract closed captions and burnt in subs in the same pass

- .gitignore
---
A lot of files that are generated by cmake and during compilation in the Rust project aren't in the `.gitignore` . This PR adds them to the `.gitignore`
> Put generated files of the rust project in the .gitignore

- src/lib_ccx/stream_functions.c
---
This pull request fixes Issue #1421, by checking if a box of type `moov` also has a valid movie header (mvhd). This might cause problems with files which do not have the header at the start of the box. I could not confirm if such files exist, but all the files I tested with do have the `mvhd` header at the start of the `moov` box. This might require some further testing, as it might cause problems with such MP4 containers which could contain another atom before the `mvhd` header.
> [FIX] Fix issue #1421

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_option.c
- src/lib_ccx/ccx_common_option.h
- src/lib_ccx/ccx_encoders_common.c
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ccx_encoders_webvtt.c
- src/lib_ccx/params.c
---
This fixes issue #1463. If enabled, the X-TIMESTAMP-MAP header is placed on the second line. There are always two newlines between the headers and body.
This also fixes the --no-timestamp-map option, which wasn't disabling the header.
I added on the commit to disable X-TIMESTAMP-MAP header by default since it is not valid WebVTT. It doesn't make sense to generate invalid WebVTT by default, especially when the input is not MPEG-TS. This is a breaking change (--no-timestamp-map becomes --timestamp-map).
> [FIX] WebVTT X-TIMESTAMP-MAP header placement (#1463)

- docs/CHANGES.TXT
- src/lib_ccx/matroska.c
---
When passed the `-stdout` flag, CCExtractor should write the subtitles to standard output, instead of an output file.
However, as noted in Issue #1453, CCExtractor doesn't respect the `-stdout` flag when multiple CC tracks are present in a Matroska input file (usually .mkv).
The commit/s in this pull request ensure/s that output is written to standard output if `-stdout` is present even if the input file is a Matroska container with multiple CC tracks.
Signed-off-by: Abhishek Kumar <abhi.kr.2100@gmail.com>
> [FIX] Fix issue #1453: Respect `-stdout` if multiple CC tracks are found in a Matroska input file

- docs/CHANGES.TXT
- src/lib_ccx/ccx_decoders_708_output.c
- src/rust/src/decoder/tv_screen.rs
---
Link to sample video: https://drive.google.com/file/d/13p6HBxGXlm0BGpaS15JwCJjfnBdm_Qbm/view?usp=sharing
Running ccextractor on the above sample video WhackedOutVideos_short.mov produces a file WhackedOutVideos_short.p0.svc01.srt with the following contents:
```
1
00:00:02,502 --> 00:00:03,636
<font color="aaaaaa">Or is this synchronized</font>
2
00:00:03,637 --> 00:00:05,971
<font color="aaaaaa">Or is this synchronized</font>
<font color="aaaaaa">stick poking?</font>
.
.
.
```
Without the `#` in color attribute of font tag, the text is rendered by black color instead of `#aaaaaa`. This PR adds the missing `#`:
```
1
00:00:02,502 --> …
```
> [FIX] Missing `#` in color attribute of font tag

- src/ccextractor.c
---
Hardsubx flag was broken by a bad commit, this PR fixes that.
> [FIX] broken -hardsubx flag

- docs/CHANGES.TXT
- src/lib_ccx/ffmpeg_intgr.c
- src/lib_ccx/hardsubx.c
- src/lib_ccx/hardsubx_decoder.c
- src/lib_ccx/ocr.c
---
CCExtractor build fails when using build_hardsubx with ffmpeg 5.0 and tesseract 5.0, This PR is for fixing the build of hardsubx with ffmpeg 5.x and tesseract 5.x.
- For FFmpeg, Basically `codec` is now deprecated in favor of `codecpar` and `av_register_all` is deprecated in many places
- For Tesseract, now the tessdata is located in /usr/share/tesseract-ocr/5/
- For Hardsubx. I have changed the code for getting the codec to fix 0x0 widthxheight error.
Resolves: #1418
> fix: ffmpeg 5 and tesseract 5 compatibility

- docs/COMPILATION.MD
- linux/build
- linux/build-debug
- linux/build-hardsubx
- linux/build_hardsubx
- linux/builddebug
---
This pull request aims to consolidate the `linux/build` script. The script now accepts 3 options, `-debug`, `-without-rust` and `-hardsubx`. The original behavior is completely intact and does not affect the workflow. This also solves the original script's shortcoming of compiling rust more gracefully than #1489 as it changes the profile based on the `-debug` flag.
> [IMPROVEMENT] `linux/build` script revamp

- src/rust/build.rs
---
#1469 brought this up where we would get some warnings when compiling the rust module without the `hardsubx_ocr` feature. As stated later in the issue these `mut`s are actually necessary when the feature is turned on. This fix is a minor change which removes the warnings in both the cases. This might allow us to maybe use `RUSTFLAGS="--deny warnings"` in our workflows to fail on warnings.
> [IMPROVEMENT] getting rid of the warnings during rust builds

- docs/CHANGES.TXT
- linux/Makefile.am
This header is generated by the pre-build.sh script.  The compilation fails if it is missing.
* linux/Makefile.am (ccextractor_SOURCES): Add ../src/lib_ccx/compile_info_real.h.
---
> [FIX] linux/Makefile.am: Add missing generated header.

- .github/workflows/build_linux.yml
- .github/workflows/format.yml
- docs/COMPILATION.MD
- docs/FFMPEG.md
- src/rust/Cargo.lock
- src/rust/Cargo.toml
---
Previously Environment variables were necessary for rsmpeg but now they aren't, https://github.com/CCExtractor/rusty_ffmpeg/pull/90
> [IMPROVEMENT] Make Environment variables for Hardsubx optional

- docs/CHANGES.TXT
- linux/build
---
Fixes https://github.com/CCExtractor/rusty_ffmpeg/issues/95
> hardsubx: Add missing `-lavfilter` for hardsubx linking

- src/lib_ccx/ccx_encoders_webvtt.c
---
This pr solves the but #1516
> [FIX] #1516 in webvtt added support to two-three-four utf-8 bytes

- docs/CHANGES.TXT
- src/lib_ccx/ccx_encoders_webvtt.c
---
Fixes #1520 so that style and text donʼt get out of sync.
I can see a few other issues (mentioned below) which I donʼt have sample files for so I can neither submit full issues nor personally fix, and fixing them might mean a rewrite of the entire loop or even the function:
* It can still have mis-nested HTML tags (it can output `normal<i>italics<u>both</i>underlined`, or even worse with colors)
* Even without `--nohtmlescape` it does not escape unsafe characters (which SRT also doesnʼt).
Fixing those probably requires a much bigger refactor than I am able to do at the moment, and probably for most cases the first wonʼt be an issue (I expect …
> [FIX] #1520 keep webvtt-full formatting in sync

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_char_encoding.c
---
The solid block character in Line-21 encoding (`0x7f`) is correctly encoded when converted to UTF-8 as `E2 96 A0` (which is `U+25A0`). But this character is missing in the conversion to latin-1 and unicode.
> [FIX] encoding of solid block in latin-1 and unicode

- docs/CHANGES.TXT
- src/lib_ccx/output.c
---
Currently this only works with field 2, which is rarely used; the issue is that field 2 is output either way and this format only supports one field.  This PR gets rid of the extraneous output; the `writeraw` function doesnʼt read XDS so it wasnʼt doing any good in this case anyway.
> [FIX] Fix McPoodle broadcast raw format output

- docs/CHANGES.TXT
- src/lib_ccx/ccx_decoders_708.c
- src/lib_ccx/ccx_dtvcc.c
- src/rust/src/decoder/mod.rs
- src/rust/src/decoder/service_decoder.rs
---
Partially Fixes #1468 
The reason why none of the text was showing up was because the given sample had service blocks of this kind:
`80 ff 8c ff 9c 18 46 19 00 1f 11 84 92 00 04 90 05 00 91 2a 00 00`
- `80` - Set Current Window to 0 - Does nothing since Window was never defined before.
- `ff` - character from G1 charset - The current implementation skips the entire packet if character is attempted to be inserted in an undefined window, which it was during this point.
- `8c ff` - Delete Windows specified with bitmap `ff` - Does nothing since no windows were defined in the first place.
- `9c ...` - Define Window 4 - Here comes the actual …
> [FIX] Incorrect skipping of packets

- src/lib_ccx/ffmpeg_intgr.h
- [ x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ x] I have checked that another pull request for this purpose does not exist.
- [ x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ x] I have used CCExtractor just a couple of times.
---
Minor typo fix
```diff
-#ifndef _FFMPEG_INTIGRATION
-#define _FFMPEG_INTIGRATION
+#ifndef …
```
> Fix typo in ffmpeg_intgr.h

- docs/COMPILATION.MD
libgpac-dev isn't available on Ubuntu 23.10 (Mantic) added a note instructing to build it from source instead.
---
The package `libgpac-dev` isn't available for the Ubuntu 23.10 Mantic release. [Package search returns no results](https://packages.ubuntu.com/search?suite=mantic&searchon=names&keywords=libgpac) which would lead the ccextractor build to fail while following the given instructions, Added a note instructing to build it from source instead.
> [FIX] Compilation.md - Added a note for Ubuntu 23.10 

- docs/CHANGES.TXT
- src/lib_ccx/mp4.c
- src/lib_ccx/stream_functions.c
On bad inputs containing e.g. the following sequence of bytes within the first 1MiB "ff ff ff ff 6d 65 74 61" `detect_stream_type` was executing an infinite loop because "ff ff ff ff" was interpreted as a length of the candidate "meta" MP4 box, caused the size_t overflow inside `isValidMP4Box` which pointed `nextBoxLocation` to the previous byte and the execution flow processed the same "meta" again.
---
> **[FIX]** fix infinite loop in MP4 file type detector and processor

- docs/COMPILATION.MD
- linux/build
---
I was getting started with the project. Just trying to build ccextractor by following the [COMPILATION.md](https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD) resulted in a linker error, which was caused due to a deprecated library name. This fixes the error on my machine.
OS: Arch linux 6.6.10 x86_64
gcc 13.2.1
clang 16.0.6
Used pacman to install all listed dependencies.
> Typo in compilation docs

- src/rust/src/decoder/window.rs
---
Cherry-picked from #1547 commit bd68411
> [FIX] Rustfmt CI failing

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_timing.c
- src/lib_ccx/ccx_common_timing.h
- src/lib_ccx/ccx_decoders_708.h
- src/lib_ccx/ccx_decoders_708_output.c
- src/lib_ccx/ccx_decoders_708_output.h
- src/rust/src/decoder/output.rs
- src/rust/src/decoder/timing.rs
- src/rust/src/decoder/tv_screen.rs
---
I have tested some of the videos and it is working.
Closes #1426 (and in order to fix #1423)
> [FEATURE] Add SCC support to CEA-708 decoder

- docs/CHANGES.TXT
- src/rust/Cargo.lock
- src/rust/Cargo.toml
---
CCExtractor uses `rsmpeg` for FFmpeg bindings and we need to update it to the latest version.
I tried building CCExtractor with `rsmpeg 0.14.2 + ffmpeg.6.1`  and it was successfull. 
Also I tested couple of videos with `hardsubx` flags and it is working fine.
This work was mentioned to be done in GSOC but since I didn't find anything lot to work, so doing it before
> Bump `rsmpeg` to latest version for `ffmpeg` bindings

- docs/COMPILATION.MD
---
{When I was compiling ccextractor on Arch linux,  a `fatal error: gpac/isomedia.h: No such file or directory` message was printed. Install gpac library to resolve this error.}
> [DOCS] Add gpac package in compilation guide on Archlinux

- src/lib_ccx/ccx_decoders_708_encoding.c
- src/lib_ccx/ccx_decoders_708_encoding.h
- src/rust/build.rs
- src/rust/src/decoder/encoding.rs
- src/rust/src/decoder/mod.rs
---
I have migrated the logic and functions from the [lib_ccx/ccx_decoder_708_encoding.c](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708_encoding.c) file to Rust, located in decoder/encoding.rs. This conversion maintains the same functionality that was originally written in C, now implemented in Rust.
To know more See [ccx_decoder_708_encoding.c](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708_encoding.c) and compare with File Changed in PR, they are both same
- **Current codebase scenerio:** Only C code of [ccx_decoder_708_encoding.c](https://github.com/CCExtractor/ccextractor …
> [FEATURE] Port 708 decoder encoding module to RUST

- docs/CHANGES.TXT
- src/lib_ccx/activity.c
- src/lib_ccx/lib_ccx.c
- src/lib_ccx/lib_ccx.h
- src/lib_ccx/utility.c
- src/rust/Cargo.lock
- src/rust/build.rs
- src/rust/lib_ccxr/Cargo.lock
- src/rust/lib_ccxr/Cargo.toml
- src/rust/lib_ccxr/src/util/log.rs
- src/rust/lib_ccxr/src/util/mod.rs
- src/rust/src/libccxr_exports/mod.rs
---
Closes #1553 
This PR adds functions and macros used for logging operations. The functions of this PR have not been integrated into the C codebase since there is no safe or easy way to pass variable number of arguments (as used in printf) from C to Rust. But the code for initializing the logger from C to Rust is included.
After this PR merge, anybody can use macros like `info!`, `fata!`, `error!`, `debug!` (Just like `mprint`, `fatal`, etc in C) for logging purposes after initializing logger using `ccxr_init_basic_logger`
> [FEAT] Add log module in lib_ccxr

- docs/CHANGES.TXT
- src/rust/lib_ccxr/src/common/constants.rs
- src/rust/lib_ccxr/src/common/mod.rs
- src/rust/lib_ccxr/src/lib.rs
---
Closes #1555 
This PR adds some common enums & constants which will be used througjout the codebase. This PR code is equivalent to `ccx_common_constants` C file.
NOTE: Most of these enums are completely unrelated to each other and the only reason they are kept together for now is because they were kept together in C codebase. In the future when appropriate modules will be built, each of them will have to tranfered to their respective meaningful modules.
>  [FEAT] Add constants module in `lib_ccxr`

- docs/CHANGES.TXT
- src/lib_ccx/ccx_common_common.c
- src/lib_ccx/ccx_common_common.h
- src/lib_ccx/utility.c
- src/lib_ccx/utility.h
- src/rust/Cargo.lock
- src/rust/lib_ccxr/Cargo.lock
- src/rust/lib_ccxr/Cargo.toml
- src/rust/lib_ccxr/src/lib.rs
- src/rust/lib_ccxr/src/time/mod.rs
- src/rust/lib_ccxr/src/time/units.rs
- src/rust/lib_ccxr/src/util/mod.rs
- src/rust/lib_ccxr/src/util/time.rs
- src/rust/src/libccxr_exports/mod.rs
- src/rust/src/libccxr_exports/time.rs
---
Closes #1556 
This PR adds types that enables to store time in different representations like simple milliseconds, number of frames, etc. And also allow to interconvert between them. It also provides functions for formatting time in different kinds of formats. Certain functions are integrated into C codebase.
In comparision with PR #1556, I initiated `lib_ccxr/utils/time.rs` for only functions mentioned in `utility.c` & `lib_ccxr/time/units.rs` for necessary implementation(struct, enums, functions) of any work related to timings.
This `lib_ccxr/time` will be continued later as well for more timings code coversion
> [FEAT] Add time units module in `lib_ccxr`

- docker/README.md
- docker/dockerfile
- docs/CHANGES.TXT
- docs/COMPILATION.MD
---
Creates Docker image for easy usage of CCExtractor without any environmental hustle
Uses alpine image to build CCExtractor in it.
> [FEATURE]: Create Docker image for CCExtractor

- src/rust/lib_ccxr/src/util/encoding.rs
- src/rust/lib_ccxr/src/util/mod.rs
---
Closes #1554 
Added a module in `lib_ccxr` for working with different kinds of text encoding formats.
This PR adds types used for representing Strings encoded in a certain format like Line 21 or UCS-2 and the ability to interconvert between them.
> [FEAT] Add encoding module in `lib_ccxr`

- .github/workflows/format.yml
- .github/workflows/test_rust.yml
- docs/CHANGES.TXT
- src/rust/lib_ccxr/src/time/units.rs
- src/rust/lib_ccxr/src/util/bits.rs
- src/rust/lib_ccxr/src/util/encoding.rs
- src/rust/lib_ccxr/src/util/levenshtein.rs
- src/rust/lib_ccxr/src/util/mod.rs
- src/rust/src/decoder/commands.rs
- src/rust/src/decoder/mod.rs
- src/rust/src/decoder/output.rs
- src/rust/src/decoder/service_decoder.rs
- src/rust/src/decoder/timing.rs
- src/rust/src/decoder/tv_screen.rs
- src/rust/src/decoder/window.rs
- src/rust/src/hardsubx/imgops.rs
- src/rust/src/hardsubx/utility.rs
- src/rust/src/lib.rs
- src/rust/src/utils.rs
---
Creating Unit test cases for rust modules(`decoder` + `hardsubx`).
Closes #911
> [FEATURE] Create unit test for rust code

- docs/CHANGES.TXT
- src/lib_ccx/ccx_demuxer_mxf.c
> [IMPROVEMENT] Ignore version check on mxf essence container

- src/lib_ccx/ccx_encoders_helpers.c
- src/lib_ccx/ccx_encoders_helpers.h
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/ccx_encoders_spupng.h
- src/rust/build.rs
- src/rust/lib_ccxr/src/common/options.rs
- src/rust/src/common.rs
- src/rust/src/lib.rs
- src/rust/src/parser.rs
- src/rust/wrapper.h
---
As SamplePlatform ran tests, some issues were encountered. This PR fixes those.
> [FIX] Issues in Tests

- src/lib_ccx/ccx_common_timing.c
- src/rust/build.rs
- src/rust/lib_ccxr/src/common/options.rs
- src/rust/lib_ccxr/src/time/c_functions.rs
- src/rust/lib_ccxr/src/time/mod.rs
- src/rust/lib_ccxr/src/time/timing.rs
- src/rust/lib_ccxr/src/time/units.rs
- src/rust/src/decoder/mod.rs
- src/rust/src/decoder/service_decoder.rs
- src/rust/src/lib.rs
- src/rust/src/libccxr_exports/mod.rs
- src/rust/src/libccxr_exports/time.rs
---
Closes #1558
This PR adds types and functions to store and calculate timing related information during the decoding process. The functions are integrated into C. 
After this PR merge, `ccx_common_timing.c` & `ccx_common_timing.h` file is completed ported to rust
> [FEAT] Add timing module in `lib_ccxr`

- docs/CHANGES.TXT
- src/lib_ccx/ocr.c
This commit fixes a compile-time error regarding an implicit declaration of mapclut_paletee() on some compilers and compiler versions.  Notably, Arch Linux and Ubuntu 24.10 seem to be affected.
The error resolved is:
```
../src/lib_ccx/ocr.c: In function 'ocr_rect':
../src/lib_ccx/ocr.c:922:9: error: implicit declaration of function 'mapclut_paletee' [-Wimplicit-function-declaration]
922 |         mapclut_paletee(palette, alpha, (uint32_t *)rect->data1, rect->nb_colors);
|         ^~~~~~~~~~~~~~~
```
This was resolved by `#include`-ing "ccx_encoders_spupng.h" in the file src/lib_ccx/ocr.c.  Thanks to GitHub user @steel-bucket for sharing the fix in this issue's comments.
I was having the same issue, and making this change to that file allowed it to compile on my system (Ubuntu 24.10, GCC …
> Fix compile-time issue involving implicit declaration of mapclut_paletee()

- src/lib_ccx/params.c
- src/rust/src/args.rs
Referring to issue #1448 
---
This pull request addresses the issue where the default behavior of ccextractor changed in version 0.94 regarding CEA-608 and CEA-708 subtitle extraction, but this change was not clearly documented.
Changes:
- Added a "Subtitle Extraction" section to the --help output in params.c to explain that ccextractor now extracts both CEA-608 and CEA-708 subtitles by default, resulting in two output files when both are present.  The section also explains how to use the -1, -2, -12, and -svc options to control which subtitle types are extracted.
- Updated CHANGES.TXT to include a more detailed description of the change in …
> [IMPROVEMENT] Clarify CEA-608/708 Subtitle Extraction Behavior #1448

- src/lib_ccx/asf_functions.c
- src/lib_ccx/ccx_decoders_common.c
- src/lib_ccx/ccx_encoders_spupng.c
- src/lib_ccx/dvb_subtitle_decoder.c
- src/lib_ccx/general_loop.c
- src/lib_ccx/hardsubx_decoder.c
- src/rust/lib_ccxr/src/util/bits.rs
- src/rust/src/decoder/encoding.rs
- src/rust/src/decoder/mod.rs
---
Fixes the C formatting issues and fixes all but one clippy warnings that are being triggered on the CI pipelines
> [FIX] Fix c formatting issues and fix some rust warnings

- src/rust/src/common.rs
- src/rust/src/lib.rs
---
Fix clippy warning due to creating mutable reference to a global variable
> Pass raw pointer to avoid mut ref to global variable warning

- src/thirdparty/freetype/gzip/ftzconf.h
- src/thirdparty/freetype/gzip/zutil.h
---
I tried compiling ccxr on mac and ran into a few problems
1. In [src/thirdparty/freetype/gzip/ftzconf.h], `typedef Byte` was not happening in case the OS was MacOS
2. Updated the prepocessor directives (in [_src/thirdparty/freetype/gzip/ftzconf.h_]) used for identifying if the OS is MacOS to newer standards : `__APPLE__` and `__MACH__`
> [FIX] Updated preprocessor directives for macOS

- src/rust/src/args.rs
- src/rust/src/parser.rs
---
Came across this issue while trying to debug #985, passing `--debugdvbsub` to a ccextractor build built with rust would error citing an unknown argument. Turned out to be a simple typo in the rust arg parser.
Here is the entry on `ccextractor --help`:
```
--debugdvbsub
Write the DVB subtitle debug traces to console
```
> fix: debugdvb arg typo

- src/rust/CMakeLists.txt
---
CMake builds have been failing recently (as seen on GH actions), this is caused due to corrosion v0.5.0 being [incompatible](https://github.com/corrosion-rs/corrosion/issues/590) with the latest [release](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html) of rustup.
This patch upgrades corrosion to [v0.5.1](https://github.com/corrosion-rs/corrosion/releases/tag/v0.5.1) to enable support.
> [FIX] CMake builds failing

- src/lib_ccx/ocr.c
---
Closes #985
DVB subtitle extraction is currently broken on the latest master build. I've verified this by testing it on the following few files:
- `09-ITV_Red_Heat.ts`  
- `2016-12-15-BBC4.ts`  
- `CHANNEL_4_2016-06-21.ts`  
- `chan7_BBC NEWS.ts`  
I've found two root issues on why this is the case:
1. The first issue is that the ocr'd text in `ocr_bitmap()` is [freed](https://github.com/CCExtractor/ccextractor/blob/a84256da017fa3c8d993262cb8a6436309fc9197/src/lib_ccx/ocr.c#L689) before being returned. Removing this free causes memory leaks (as pointed out by #1511).
2. The second issue lies within the `quantize_map()` function
- Passing …
> [FIX] DVB OCR: Memory Leak & Quantization Issues

- docs/CHANGES.TXT
- src/lib_ccx/matroska.c
- src/lib_ccx/matroska.h
**In raising this pull request, I confirm the following:**
**My familiarity with the project is as follows:**
---
Introduced improved handling of language tags in the Matroska parser. It addresses an issue where IETF BCP47 language tags (e.g., "en-US") were not being correctly processed, leading to potential segmentation faults and inaccurate subtitle extraction. Like in issue #1665
Modern Matroska (MKV) files are increasingly using IETF BCP47 language tags to identify subtitle tracks. These tags offer more precision than the traditional 3-letter ISO 639-2 codes, allowing for specification of regional variations, scripts, and other linguistic details (e.g., `en-GB` for British English, `es-MX` for Mexican Spanish).
The existing parser was primarily designed for the older 3-letter codes …
> [FIX] Issue#1665 Enhanced Matroska Language Tag Handling

- src/rust/src/decoder/window.rs
---
This PR resolves the warning posed by depreciated module `std::intrinsics` by replacing the same with `std::mem` module
```
error: use of deprecated module `std::intrinsics`: import this function via `std::mem` instead
--> src/decoder/window.rs:15:17
|
15 |     intrinsics::copy_nonoverlapping,
|                 ^^^^^^^^^^^^^^^^^^^
|
```
> [FIX] Replaced deprecated module `std::intrinsics` with `std::ptr`

- linux/build
**[FIX]** Corrected bitness check and added help option to build script
---
Fixed an issue in the bitness check in `linux/build.sh`:
```bash
if [ "$bit_os"=="64" ]
```
Fixed missing spaces around `==` in bitness check. Without the spaces, the condition always evaluated to true, causing `-DGPAC_64_BITS` to be added even on non-64-bit systems.
> [FIX] Corrected bitness check for 64-bit systems

- docs/COMPILATION.MD
- src/thirdparty/libpng/pngpriv.h
- src/thirdparty/zlib/zutil.h
---
Recently updated to macOS@15.4 on M1 Mac and CCExtractor compilation started failing for all 3 methods in [src/COMPILATION.MD](https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD).
The issue was due to some update in Xcode command-line-tools which updated clang to `Apple clang version 17.0.0 (clang-1700.0.13.3)`
Updating these preprocessor directives in third party libs solves the issue : 
- src/thirdparty/libpng/pngpriv.h
- src/thirdparty/zlib/zutil.h
Also updated dependencies(`brew install cmake gpac`) in src/docs/COMPILATION.MD
> [FIX] Fix compilation on silicon mac

- docker/dockerfile
- docs/CHANGES.TXT
- linux/build
---
**Changes:**
- Replaced `cd` commands with `WORKDIR` instructions to improve clarity and follow Docker best practices.
- Removed the unused RUN export for LIB_CLANG_PATH, which only affected a single build layer (since export does not persist between Docker layers); the library is automatically detected during build.
- Parallelized GPAC build using `make -j$(nproc)`, significantly reducing build time.
- Removed redundant `CMD` instruction since `ENTRYPOINT` already defines the execution command.
This PR improves Dockerfile structure, reduces build time, and eliminates unnecessary instructions for a cleaner and more maintainable setup.
> [IMPROVEMENT] Refactor and optimize Dockerfile

- src/rust/Cargo.lock
- src/rust/Cargo.toml
- src/rust/src/decoder/tv_screen.rs
---
Closes #1697 
The iconv [crate](https://github.com/andelf/rust-iconv) is currently unmaintained and broken on the latest version of rust (see this [issue](https://github.com/andelf/rust-iconv/issues/10)). This PR migrates the encoding from iconv to the well maintained [encoding_rs](https://crates.io/crates/encoding_rs) library.
Note that the rust implementation for this particular case was and still is buggy, regression tests 142, 147 and 149 all of which test this specific scenario have historically had empty output files (see [here](https://sampleplatform.ccextractor.org/regression/test/142/view) for eg), which is why the tests were passing. …
> fix: replace iconv with encoding_rs

- docs/CHANGES.TXT
- src/rust/src/decoder/mod.rs
- src/rust/src/lib.rs
---
While working on the `share` module, I came across the problem that on the main branch, [the Unit Test Rust(test_rust.yml) was failing](https://github.com/CCExtractor/ccextractor/actions/runs/14557403272/job/40836138898). Reverting commits didn't help, later I found out that the problem was due to Rust being upgraded to 1.86.0.
[The New Changes to check for Null pointer De-referencing](https://github.com/rust-lang/rust/pull/134424)
This triggered a panic on 3 tests
- `test_do_cb` in `src/rust/src/lib.rs`
- `test_process_cc_data` in `src/rust/src/decoder.rs`
- `test_process_current_packet` in `src/rust/src/decoder.rs`
The errors were fixed by …
> [FIX] Fixed Unit Test Rust based on the new changes on Rust 1.86.0

- .github/workflows/build_windows.yml
---
The Windows build workflow was not triggering for pull requests or commits that only modified Rust files due to the paths filter missing those files; this prevented the sample platform from running Windows tests, which rely on the build artifact produced by that workflow.
> fix: windows builds not triggering on rust changes

- docs/CHANGES.TXT
- src/rust/lib_ccxr/src/activity.rs
- src/rust/lib_ccxr/src/teletext.rs
- src/rust/lib_ccxr/src/time/units.rs
- src/rust/lib_ccxr/src/util/bits.rs
- src/rust/lib_ccxr/src/util/log.rs
- src/rust/src/decoder/timing.rs
- src/rust/src/decoder/tv_screen.rs
- src/rust/src/lib.rs
- src/rust/src/parser.rs
---
Clippy has introduced a new formatting scheme on the New rust version 1.88 which caused clippy to fail.
This PR fixes those issues. I was notified of this from @hrideshmg 's branch [failing CI](https://github.com/CCExtractor/ccextractor/actions/runs/15909554037/job/44873167652)
> Fixed Clippy Errors on 1.88

- src/rust/lib_ccxr/src/time/timing.rs
- src/rust/lib_ccxr/src/time/units.rs
- src/rust/src/lib.rs
- src/rust/src/libccxr_exports/time.rs
- src/rust/src/parser.rs
---
Cargo tests have been failing on Windows on the master branch for a while now. The primary reason seems to be differences in linking behaviour between the GNU and MSVC ABIs, see [here](https://rust-lang.github.io/rustup/installation/windows.html#:%7E:text=Or%20to%20choose%20the%2064%20bit%20GNU%20toolchain) for more info.
The main issue was that when running unit tests, the linker that MSVC uses couldn't resolve several external C symbols, primarily [these](https://github.com/CCExtractor/ccextractor/blob/407d0f4e93611c5b0ceb14b7fc01d4a4c2e90433/src/rust/src/lib.rs#L60-L77). This makes sense as when running unit tests, the C side of the codebase …
> [FIX] cargo tests failing on windows

- docs/CHANGES.TXT
- src/rust/src/decoder/service_decoder.rs
---
The regression tests under the XDS category have been failing on Windows due to segmentation faults for a while now. The cause for these errors stem from a small mistake that was made when the CEA-708 decoder functions were ported to Rust.
In specific, here is the offending [line](https://github.com/hrideshmg/ccextractor/blob/54dfce4c89245f71b4ffc71e099e6298550a1cd5/src/rust/src/decoder/service_decoder.rs#L1139):
```Rust
// Add symbol to window
window.rows[window.pen_row as usize] = Box::into_raw(Box::new(sym));
```
To contrast, here is the equivalent C [section](https://github.com/hrideshmg/ccextractor/blob/54dfce4c89245f71b4ffc71e099e6298550a1 …
> fix: XDS segmentation faults

- docs/CHANGES.TXT
- src/ccextractor.c
---
CCextractor currently fails when an elementary stream is passed or `--in=es` is specified. This is caused by the addition of a break statement in a switch case that was meant to fall through and start the general loop.
> fix: elementary stream regressions

- docs/CHANGES.TXT
- src/ccextractor.c
---
Removes the API structures from `ccextractor.c`. This was causing a regression due to mismatch between the options maintained by `api_options` and `ccx_options`.
> refactor: remove api structures

- src/rust/src/libccxr_exports/bitstream.rs
---
This PR fixes a bug where an "exhausted" C bitstream (one that has been fully read, where pos == end) would lose its buffer context when converted to Rust and back. The current logic treats this state the same as an uninitialized stream  causing the original buffer location to be lost.
The fix ensures that even an exhausted stream creates a zero-length Rust slice that retains the original base pointer so that the pointers are preserved during the conversions.
> fix: rust bitstream segfault

- src/lib_ccx/hardsubx.c
Fix build with ffmpeg 8
- [ x] I have checked that another pull request for this purpose does not exist.
- [ x] I have considered, and confirmed that this submission will be valuable to others.
- [ x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ x] I give this submission freely, and claim no ownership to its content.
> Fix build with ffmpeg 8

- src/lib_ccx/ocr.c
---
Was caused by CCExtractor not being able to find the location of the tessdata folder on windows.
> Fix DVB Regressions on windows

- src/rust/lib_ccxr/src/common/options.rs
- src/rust/src/common.rs
- src/rust/src/parser.rs
---
The `--ocrlang` argument currently doesn't work as expected as it expects to be passed a file path on Rust but the rest of the codebase expects it to be language code of the `.traineddata` file
> Fix `--ocrlang` argument on rust

- .github/workflows/build_linux.yml
- docs/CHANGES.TXT
- src/rust/src/hardsubx/decoder.rs
- src/rust/src/hardsubx/imgops.rs
---
closes #1723 
Hardsubx is currently broken on the master branch on Rust.
Fixed a segmentation faults on Linux which was caused by a null pointer dereference in `dispatch_classifier_function`, I've added proper error handling to fix this. While here, I also noticed that the values in the match statement for the classifier functions are incorrect, see [here](https://github.com/hrideshmg/ccextractor/blob/97e74447da106ceebf02afb20804c47c21a7d3af/src/lib_ccx/hardsubx.h#L27). The `pixDilateGray()` function also had an incorrect argument, see [here](https://github.com/hrideshmg/ccextractor/blob/hardsubx_fixes/src/lib_ccx/hardsubx_decoder.c#L56).
While …
> Fix Hardsubx OCR

- docker/dockerfile
---
GPAC renamed its libraries to `libgpac.so.13` causing image build  to fail:
```
Error: building at STEP "COPY --from=builder /usr/local/lib/libgpac.so.12 /usr/local/lib/": checking on sources under "/home/pszemus/.local/share/containers/storage/overlay/faa4f2b5c39251a5cf42a97234d2d5652336a2388c96a64d85fc1922c4c43a71/merged": copier: stat: "/usr/local/lib/libgpac.so.12": no such file or directory
```
so let's fix the gpac version to the latest release (2.4.0)
> [FIX] dockerfile: fix gpac version to 2.4.0

- src/rust/src/hardsubx/imgops.rs
---
Hardsubx in rust currently does not give identical output as the C implementation, often providing inferior results. After debugging for a bit I noticed that there were very slight differences in the luminance masks between both versions. 
In the old C code, the RGB to LAB conversion was done [manually](https://github.com/hrideshmg/ccextractor/blob/ocr_fixes/src/lib_ccx/hardsubx_imgops.c#L69), in rust we [now](https://github.com/hrideshmg/ccextractor/blob/master/src/rust/src/hardsubx/imgops.rs#L15) use the `palette` crate for this purpose. 
The `Srgb` implementation from `palette` we were using till now assumes that the input image is [gamma …
> fix: ocr luminance calculation fix

- docs/CHANGES.TXT
- src/CMakeLists.txt
- src/lib_ccx/ccx_common_platform.h
- src/lib_ccx/ccx_encoders_common.h
- src/lib_ccx/ts_tables_epg.c
- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that another pull request for this purpose does not exist.
- [X ] I have considered, and confirmed that this submission will be valuable to others.
- [X ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X ] I give this submission freely, and claim no ownership to its content.
- [X ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**
- [X ] I am an active …
> [FIX] Fixed issue with cross compiling using MINGW-w64

- src/rust/src/es/pic.rs
---
Rust Format SourceCode Fails on 1.90. Minor change to fix it.
> Fix: Rust Clippy failing on 1.90
